### ISSUE TITLE
[UPDATE] skin.phenomenal 4.2.8

### ISSUE THREAD

**Issue by tomer953** [xbmc/repo-skins#112]
*addon - skin.phenomenal
*version - 4.2.8
*url - https://github.com/tomer953/skin.phenomenal
*branch - master
*xbmc version - Krypton

very small fixes.. 
Thank you

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/2fe4a35da5b1bb909eb81e835c7f1e3a0a323d1d

**Comment by tomer953** [comment]
hey ronie,
sorry for that, but I forgot to update some id number, after I added a new button to the skin.

very minor change but important to a lot.
could you update it please?

*version - 4.2.8.1

thanks, and sorry :)

**Comment by ronie** [comment]
if you're in a hurry, please create a pr and i'll merge it.

due to being at devcon, issue request will have to wait till next week i;m afraid.

**Comment by ronie** [comment]
done: https://github.com/xbmc/repo-skins/commit/16fac9fc1fb69d50b89198ab770b5e060b4c30cd
