### ISSUE TITLE
[Update] skin.pellucid

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#12]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 1.0.2
- Kodi/repository version: Krypton
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: 97d736657c9e1ce57c59c4090b270d96a490a034
- Branch: Krypton

### Description of changes:
- Skin shortcuts addon is now a skin dependency 
- Minor bug fixes
- Extra colour themes added

### Checklist:
- [ x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [ x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/c288732e08647ae02e0dde722504b97ac6abe4ff
