### ISSUE TITLE
[UPDATE] skin.pellucid V1.3.3

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#128]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 1.3.3
- Kodi/repository version: Krypton
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: 4dc1f4b9733d8a5e77b335df46bfe8e532960b6e
- Branch: master

### Description of changes:
- [FIXED] Weather label showing on homescreen even if no weather plugin enabled.
- Minor tweaks

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/c397f9abaec837448b1f25dc029ef6dbf924e953
