### ISSUE TITLE
[BRANCH] skin.sio2 (Leia)

### ISSUE THREAD

**Issue by fastcolors** [xbmc/repo-skins#134]
### Add-on details:

- **General**
  - Add-on name: sio2
  - Add-on ID: skin.sio2
  - Version number: 5.0.0
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/fastcolors/skin.sio2/tree/Leia
  - Revision/tag: 6f5ed33
  - Branch: Leia

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
thanx for submitting Sio2 to the Leia repo!
i did a few checks and came up with a few items that require your attention:


addon.xml: 
path to screenshots is not correct

DialogPVRChannelManager.xml, line 169: 
missing closing bracket ```>```

Includes_Variables.xml line 83: 
use ```&amp;``` instead of ```&```


**Undefined Includes**
DialogFavourites.xml: 
```<include>Sets</include>```

MyMusicPlaylistEditor.xml: 
```<include>HeadingL</include>```

MyPVRSearch.xml: 
```<include>statusbiglist</include>```

MyPVRSearch.xml: 
```<include>statusbiglist</include>```

MyVideoNav.xml: 
```<include>moviebanners</include>```

MyVideoPlaylist.xml: 
```<include>LargeListSlider</include>```

script-globalsearch-main.xml: 
```<include>WindowOpenClose</include>```


**Undefined IDs**
Home.xml (315): 
```<ondown condition="Control.IsVisible(315)">315</ondown>```

Home.xml (317): 
```<ondown condition="Control.IsVisible(317)">317</ondown>```

Includes_Expressions.xml (317): 
```[Container(317).HasFocus + [Container(317).Position(0) | Container(317).Position(1)]]```

Includes.xml (340):
```<visible>!Control.HasFocus(340) + Player.HasMedia + ![Window.IsActive(DialogBusy.xml) | Window.IsActive(VideoFullscreen.xml) | Window.IsActive(myPVR.xml)]</visible>```

Includes_Variables.xml (344): 
```<value condition="Container(9000).HasFocus(344)"> </value>```

Includes_Variables.xml (355): 
```<value condition="Container(9000).HasFocus(355)"> </value>```

VideoOSD.xml (10123/10124/10125): 
```<visible>!Window.IsVisible(subtitlesearch) + !Window.IsVisible(10123) + !Window.IsVisible(10124) + !Window.IsVisible(10125)</visible>```

VideoOSD.xml (10123/10124/10125): 
```<visible>!Window.IsVisible(10123) + !Window.IsVisible(10124) + !Window.IsVisible(10125) + !Window.IsVisible(Dialogselect.xml)</visible>```


**Labels Not Localized**
CustomAddonShelfcustomizer_1617.xml: 
Customize

CustomnNewMusic_1123.xml: 
Browse

CustomnNewMusic_1123.xml: 
NEW ALBUM

CustomnNewMusic_1123.xml: 
NEW ALBUM

CustomnNewMusic_1123.xml: 
Hot Tracks

DialogButtonMenu.xml: 
logoff

DialogButtonMenu.xml: 
timer

DialogVideoInfo.xml: 
Rate Movie

Includes.xml: 
EPG

Includes.xml: 
New Music

Includes.xml: 
Party Mode

Includes.xml: 
Find More

Includes.xml: 
Stereo Upmix

Includes.xml: 
Passthrough

Includes_Shelf.xml: 
New Episode

Includes_Shelf.xml: 
New Episode

MyPVRTimers.xml: 
DATE

MyVideoNav.xml: 
Artwork

script-skinshortcuts.xml: 
Set Viewtype

script-skinshortcuts.xml: 
Long Press to Edit Item

script-skinshortcuts.xml: 
Max Item Number

SkinSettings.xml: 
show fanart

**Comment by fastcolors** [comment]
Thank you for checking this out!!

TBH I've submitted so I have your list of things to fix, since being "inside" the code I get lost :-)

Will try and fix everything!

**Comment by fastcolors** [comment]
https://github.com/fastcolors/skin.sio2/commit/4658c75c4c7e02df28f385d40a885df91985e7cc

all the list should be fixed <3

cheers, and thanks again for all the help and kindness you always show me!!!

**Comment by ronie** [comment]
great thanx for the rapid response!

i've done another round of testing and these should hopefully be the last ones:

**Undefined Vars:**
script-skinshortcuts-includes.xml:
```<property name="widgetPath">$VAR[movieshelf]</property>```

script-skinshortcuts-includes.xml:
```<property name="widgetPath">$VAR[movieshelf]</property>```

script-skinshortcuts-includes.xml:
```<property name="widgetPath">$VAR[epshelf]</property>```

script-skinshortcuts-includes.xml:
```<property name="widgetPath">$VAR[epshelf]</property>```


**Undefined IDs:**
GameOSD.xml:
```<visible>!Window.IsActive(1101) + !Window.IsActive(GameVideoFilter) + !Window.IsActive(GameViewMode) + !Window.IsActive(GameControllers)</visible>```

GameOSD.xml:
```<onclick>ActivateWindow(1101)</onclick>```

VideoOSD.xml:
```<visible>!Window.IsVisible(10123) + !Window.IsVisible(osdvideosettings) + !Window.IsVisible(osdaudiosettings) + !Window.IsVisible(Dialogselect.xml)</visible>```


**Untranslated Labels:**
CustomnNewMusic_1123.xml:
Browse

Includes.xml:
[UPPERCASE]suono[/UPPERCASE]


**Themes**
please remove media/Dark.xbt
see: http://kodi.wiki/view/Add-on_rules#Requirements_for_skins on how to submit skin themes


**Home.xml - onClick is not a valid animation type**
```<animation effect="zoom" start="100" end="322" time="120" center="180,208" tween="Back" easing="Out">onClick</animation>```


**CommonViews.xml - don't think you can use a $VAR[] there**
Error parsing boolean expression ```!string.isempty(listitem.mpaa) + !string.isequal($var[mpaas],na)```


**Home.xml - something is not quite right.. likely related to filling the content of the top widget**

18:02:19.364 T:140146855504256   DEBUG: CDirectoryProvider[RunScript(script.globalsearch)]: refreshing..
18:02:19.364 T:140145644898048   ERROR: GetDirectory - Error getting RunScript(script.globalsearch)

18:02:42.207 T:140146855504256   DEBUG: CDirectoryProvider[SetFocus(10040)]: refreshing..
18:02:42.207 T:140144271140608   ERROR: GetDirectory - Error getting SetFocus(10040)

18:02:48.665 T:140146855504256   DEBUG: CDirectoryProvider[ShutdownMenu]: refreshing..
18:02:48.666 T:140144279533312   ERROR: GetDirectory - Error getting ShutdownMenu

18:02:49.490 T:140146855504256   DEBUG: CDirectoryProvider[]: refreshing..
18:02:49.490 T:140144279533312   ERROR: GetDirectory - Error getting

18:02:46.482 T:140146855504256   DEBUG: CDirectoryProvider[root]: refreshing..
18:02:46.482 T:140144279533312   ERROR: GetDirectory - Error getting root



**MyPics.xml - missing content**
ERROR: Control 53 in window 10002 has been asked to focus, but it can't
![screenshot003](https://user-images.githubusercontent.com/687265/34121059-143f05a2-e428-11e7-8589-c15b8b7f0400.png)


**DialogPVRGroupManager.xml - mising background?**
![screenshot001](https://user-images.githubusercontent.com/687265/34121067-188f0864-e428-11e7-837c-29e2e0633132.png)


**EPG Guide - missing labels**
![screenshot002](https://user-images.githubusercontent.com/687265/34121077-1df47e56-e428-11e7-91a0-139d8142f86e.png)

**Comment by fastcolors** [comment]
sorry for the delay... newborn in action. time stills.

everything should be fixed in latest Leia branch commit...

**Comment by ronie** [comment]
no worries, i figured as much :-)
enjoy!

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-skins/commit/7abc188127b0a1f22978178117b4a64c115db29c
