### ISSUE TITLE
[Release] skin.andromeda 1.0.0

### ISSUE THREAD

**Issue by Tgxcorporation** [xbmc/repo-skins#157]
### Add-on details:
- **General**
  - Add-on name: Andromeda
  - Add-on ID: skin.andromeda
  - Version number: 1.0.0
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/Tgxcorporation/skin.andromeda
  - Revision/tag: fbf9b04fe26b1ec63307bb10a001fa01a9ee50bc
  - Branch: krypton

### Description of changes:

- Initial Release 

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [Andromeda](https://github.com/Tgxcorporation/skin.andromeda/wiki) wiki page.
- Development questions can be asked in the [Andromeda](https://forum.kodi.tv/showthread.php?tid=311074) section on the Kodi forum.

**Comment by ronie** [comment]
thx!

could you check these issues (for both krypton & leia):

Variable not defined: Picked.Highlight.Color  <- need capital L
1080i/Includes_Home_Common.xml: line 246

Variable not defined: Picked.Highlight.Color
1080i/Includes_Home_Common.xml: line 253

Brackets do not match: ![[Window.IsVisible(DialogExtendedProgressBar.xml)|Window.IsVisible(DialogBusy.xml)|Window.IsVisible(DialogNotification.xml)]
1080i/Includes_Animations.xml: line 28

Brackets do not match: [[Window.IsVisible(DialogExtendedProgressBar.xml)|Window.IsVisible(DialogBusy.xml)|Window.IsVisible(DialogNotification.xml)]
1080i/Includes_Animations.xml: line 32

Brackets do not match: ![[Window.IsVisible(DialogExtendedProgressBar.xml)|Window.IsVisible(DialogBusy.xml)|Window.IsVisible(DialogNotification.xml)]
1080i/Includes_Animations.xml: line 46

Brackets do not match: [[Window.IsVisible(DialogExtendedProgressBar.xml)|Window.IsVisible(DialogBusy.xml)|Window.IsVisible(DialogNotification.xml)]
1080i/Includes_Animations.xml: line 49

**Comment by Tgxcorporation** [comment]
Fixed errors! 
Revision/Tag: 47cea5725e1fd575d5c83df4b96778f6b0973fe8

Thanks

Tgx

**Comment by ronie** [comment]
added thx!
https://github.com/xbmc/repo-skins/commit/e3146ac74a3ccc7b09db6b100bb91f7da185abdd
