### ISSUE TITLE
[Release] skin.andromeda 2.0.0

### ISSUE THREAD

**Issue by Tgxcorporation** [xbmc/repo-skins#158]
### Add-on details:
- **General**
  - Add-on name: Andromeda
  - Add-on ID: skin.andromeda
  - Version number: 2.0.0
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/Tgxcorporation/skin.andromeda
  - Revision/tag: 7dd14632b0a999a5816d9f5c2d53291d0c870200
  - Branch: master

### Description of changes:

- Leia Support.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [Andromeda](https://github.com/Tgxcorporation/skin.andromeda/wiki) wiki page.
- Development questions can be asked in the [Andromeda](https://forum.kodi.tv/showthread.php?tid=311074) section on the Kodi forum.

**Comment by Tgxcorporation** [comment]
Fixed errors! 
Revision/Tag: d408b7e8bda6aea9df18f1c86443cce7f4e81675

Thanks

Tgx

**Comment by ronie** [comment]
added thx!
