### ISSUE TITLE
[skin.quartz] 5.4.0

### ISSUE THREAD

**Issue by nonJon** [xbmc/repo-skins#164]
### Add-on details:

- **General**
  - Add-on name: Quartz
  - Add-on ID: skin.quartz
  - Version number: 5.4.0
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/nonJon/skin.quartz
  - Revision/tag: fe89cc3
  - Branch: master

### Description of changes:
Updated version of a classic skin last seen in the Gotham repo.  This submission has been blessed by the author: pecinko.  

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by nonJon** [comment]
Thanks ronie.  Better than expected considering how much baggage this skin carries with it. ;-)

**Comment by nonJon** [comment]
everything should be fixed 7f1d83d  thx

**Comment by nonJon** [comment]
forgot something darn it.  pls wait for another commit.

**Comment by nonJon** [comment]
last one fe89cc3

**Comment by ronie** [comment]
thanx for the quick fixes!

the skin has been added to the leia repo.
https://github.com/xbmc/repo-skins/commit/95cc95bed548576f87dc02e236017779a52b00ba
