### ISSUE TITLE
[UPDATE] skin.pellucid

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#167]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 2.0.0
- Kodi/repository version: Leia
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: f0a5d3996d402a9fb0525b8e8bb3ff9cdbca2cec
- Branch: master

### Description of changes:
- Update of skin for Kodi Leia

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by chrisbevan** [comment]
Sorry to nag. Any update on this?

**Comment by Rechi** [comment]
Can you open a PR, would make things easier for us.

**Comment by ronie** [comment]
apologies, it took me a bit before i had some time to look into it.

could you please check these issues:
Font not defined: itemSubtitle (case-sensitive issue)
1080i/FileManager.xml: line 65

Font not defined: itemSubtitle (case-sensitive issue)
1080i/FileManager.xml: line 149

Font not defined: itemSubtitle (case-sensitive issue)
1080i/MyPrograms.xml: line 65

Font not defined: itemSubtitle (case-sensitive issue)
1080i/MyPrograms.xml: line 111

Label not translated: Shuffle
1080i/Includes_hubOptionsItems.xml: line 156

Label not defined: 15020
1080i/DialogAudioDSPManager.xml: line 46

Label not defined: 15064
1080i/DialogAudioDSPManager.xml: line 233

Invalid multiple tags for control: <height>
1080i/Home.xml: line 269

Invalid attribute for <defaultcontrol>: allways
1080i/MyMusicPlaylistEditor.xml: line 3

Could not find texture 'UIControls/PointerFo.png' (case-sensitive issue)
1080i/Pointer.xml: line 20

Could not find texture 'colors/white.jpg'
1080i/custom_musicPlayerFullscreen.xml: line 18

**Comment by chrisbevan** [comment]
Thanks Ronie. Fixed in latest commit: ed96fdda926ea6bc83ad8b369253233463b63e2b

**Comment by ronie** [comment]
added to the leia repo, thx!
https://github.com/xbmc/repo-skins/commit/7a97931687477139c9ce631cfde9732f8d7ba6a2
