### ISSUE TITLE
[Update] skin.mimic

### ISSUE THREAD

**Issue by braz96** [xbmc/repo-skins#18]
### Add-on details:

- **General**
  - Add-on name: Mimic
  - Add-on ID: skin.mimic
  - Version number: 5.0.2
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/braz96/skin.mimic
  - Revision/tag: 6cfa08ac8cb3112d3b19f249d2f2d61a5cf897b0
  - Branch: master

### Description of changes:

- Added background overlay options.
- Added new widget styles based on content type.
- Reconfigured lyrics, thx manfeed!.
- Enabled "More" menu for video widgets.
- Fixed home backgrounds for submenu items.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/cd9d169d9e27d7c0dc03ef9ded581d3c979f822f
