### ISSUE TITLE
[Update] skin.eminence.2

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/repo-skins#183]
New submission for Leia version of Eminence.

### Add-on details:

- **General**
  - Add-on name: Eminence
  - Add-on ID: skin.eminence.2
  - Version number: 3.0.1
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/jurialmunkey/skin.eminence.2
  - Revision/tag: 7a2c7981fa4fd4972c97169e9d9d49b22bedd535
  - Branch: master

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by jurialmunkey** [comment]
Sorry, I forgot the Select dialog for the Games filters. Can you take revision the latest revision instead:
864971da216a36c38a584eb6a84f22751cd46491

**Comment by Rechi** [comment]
@jurialmunkey please migrate to the new language directory structure as described at https://kodi.wiki/view/Language_support#Layout_of_the_language_folders.

Basically it is renaming `language/English` to `language/resource.language.en_gb` and the same for the other languages.

**Comment by ronie** [comment]
also there's a tool available to do the conversion for you:
https://forum.kodi.tv/showthread.php?tid=332789

**Comment by ronie** [comment]
could you please have a look at these?

Label not translated: Customise showcase widgets
SkinSettings.xml: line 267

Anything related to DSP should be removed, Kodi no longer has support for it
(https://forum.kodi.tv/showthread.php?tid=298565&pid=2785902#pid2785902)

The use of `noop` as a texture value is not valid
use `<texture></texture>` instead

**Comment by jurialmunkey** [comment]
Okay, all done. Please take latest master - commit 2ed25edd7547aba351d174f1890edb6e3dcfc415
https://github.com/jurialmunkey/skin.eminence.2/commit/2ed25edd7547aba351d174f1890edb6e3dcfc415

**Comment by jurialmunkey** [comment]
Sorry, hold-up. Noticed a bug in DialogAddonSettings where the buttons aren't working.

**Comment by ronie** [comment]
only one noop left ;-)

Includes_image.xml, line 190:
`<value condition="Skin.HasSetting(Indicator.UnwatchedEpisodes) + Integer.IsGreater(ListItem.Property(UnWatchedEpisodes),0) + [Container.Content(tvshows) | Container.Content(seasons)]">noop</value>`

**Comment by jurialmunkey** [comment]
Oops! Can't believe I missed that one. 
Fixed on latest master: 
https://github.com/jurialmunkey/skin.eminence.2/commit/a03a51ad58b62f65f7f47cc4bcf567406579278e

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-skins/commit/111ee9249e6d5b8197ac8dd617cf091b86169e8e
