### ISSUE TITLE
[Update] skin.aura

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/repo-skins#186]
### Add-on details:

- **General**
  - Add-on name: Aura
  - Add-on ID: skin.aura
  - Version number: 1.0.0
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/jurialmunkey/skin.aura
  - Revision/tag: 26ad6d0c49f1f1e634a47fae578bccfc7aa83fde
  - Branch: master

### Description of changes:

Aura skin for Leia.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by jurialmunkey** [comment]
Pushed a fixed. Please take latest revision
https://github.com/jurialmunkey/skin.aura/commit/296a37a530e26cc43a6b139b10b62c6daf50b84d

**Comment by ronie** [comment]
cheers, i took it for a test ride and bumped into these:

Label not defined: 161
1080i/Includes_Weather.xml: line 274
1080i/Includes_Weather.xml: line 294

Window ID not defined: 10025
1080i/Includes_Topbar.xml: line 174
1080i/Includes_Topbar.xml: line 211
1080i/Includes_Global.xml: line 27
1080i/Includes_Global.xml: line 85
(it's recommended to use window names instead of id's)

invalid attribute for <defaultcontrol>: allways
1080i/MyMusicPlaylistEditor.xml: line 4


also, would be nice if you could fill in the `<source>` tag in your addon.xml file

**Comment by jurialmunkey** [comment]
All fixed on latest :)
https://github.com/jurialmunkey/skin.aura/commit/75e4495241ba445e4fd4b4b11d7a702ef3f897b7

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-skins/commit/df4c91bd6e419509367997191940a61feff14721

**Comment by tomtomclub** [comment]
Not working on Intel 64 gemini lake
