### ISSUE TITLE
[Update] skin.andromeda 2.0.1

### ISSUE THREAD

**Issue by Tgxcorporation** [xbmc/repo-skins#194]
### Add-on details:
- **General**
  - Add-on name: Andromeda
  - Add-on ID: skin.andromeda
  - Version number: 2.0.1
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/Tgxcorporation/skin.andromeda
  - Revision/tag: 5fc9ff0afb3ee79175ee7f928dceec6a3acacf5d
  - Branch: master

### Description of changes:

- Leia Support.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [Andromeda](https://github.com/Tgxcorporation/skin.andromeda/wiki) wiki page.
- Development questions can be asked in the [Andromeda](https://forum.kodi.tv/showthread.php?tid=311074) section on the Kodi forum.

**Comment by ronie** [comment]
hey tgx, thanx for submitting your skins to the leia repo!

i took Andromeda for a test ride and noticed these along the way:

addon.xml:
please bump xbmc.gui to 5.14.0

rename DialogPVRGuideOSD.xml to DialogPVRChannelGuide.xml
see: https://forum.kodi.tv/showthread.php?tid=298565&pid=2550314#pid2550314

just in case (not mandatory) you want to support games, this file is missing:
MyGames.xml

the globalsearch addon has been fully rewritten for leia and does not use these files anymore:
script-globalsearch-main.xml
script-globalsearch-infodialog.xml
see: https://forum.kodi.tv/showthread.php?tid=326903

remove reference to DSP, it's no longer supported in Kodi:
1080i/VideoOSD.xml: line 26
see: https://forum.kodi.tv/showthread.php?tid=298565&pid=2785902#pid2785902

Include not defined: Info_50_BigList
1080i/MyPVRGuide.xml: line 265
1080i/MyPVRGuide.xml: line 294
1080i/MyPVRGuide.xml: line 323
i think you can remove the enitire NOW/NEXT/CHANNEL section there

Window ID not defined: 56
1080i/Includes_Variables.xml: line 63

Label not defined: 416
1080i/script-script.extendedinfo-DialogVideoInfo.xml: line 621
1080i/script-script.extendedinfo-DialogVideoInfo.xml: line 2080
1080i/script-script.extendedinfo-DialogInfo.xml: line 158
1080i/DialogAddonInfo.xml: line 210
1080i/Includes_Weather.xml: line 8

Label not defined: 35504
1080i/DialogPeripheralManager.xml: line 59
1080i/DialogPeripheralManager.xml: line 98

Label not defined: 35503
1080i/DialogPeripheralManager.xml: line 59
1080i/DialogPeripheralManager.xml: line 98

Label not defined: 35501
1080i/DialogPeripheralManager.xml: line 68
1080i/DialogPeripheralManager.xml: line 108

Label not defined: 35013
1080i/DialogGameControllers.xml: line 80

Label not defined: 15020
1080i/DialogAudioDSPManager.xml: line 24

Label not defined: 15064
1080i/DialogAudioDSPManager.xml: line 111

Label not defined: 31438
1080i/script-skin_helper_service-ColorPicker.xml: line 87

...and last but not least, `-` is not a valid texture name
see: https://forum.kodi.tv/showthread.php?tid=298565&pid=2534486#pid2534486
defaults.xml:        <texturenofocus>-</texturenofocus>
defaults.xml:        <texturenofocus>-</texturenofocus>
defaults.xml:        <alttexturenofocus>-</alttexturenofocus>
defaults.xml:        <texturenofocus>-</texturenofocus>
defaults.xml:        <texturenofocus>-</texturenofocus>
defaults.xml:        <texturenofocus>-</texturenofocus>
defaults.xml:        <texturenofocus>-</texturenofocus>
DialogContextMenu.xml:                <texture border="5">-</texture>
DialogNotification.xml:                    <texture>-</texture>
Includes.xml:        <alttexturefocus>-</alttexturefocus>
Includes.xml:                <texture>-</texture>
Includes.xml:        <alttexturenofocus>-</alttexturenofocus>
Includes.xml:        <texturesliderbackground>-</texturesliderbackground>
Includes.xml:        <textureslidernib>-</textureslidernib>
Includes.xml:        <textureslidernibfocus>-</textureslidernibfocus>
Includes.xml:        <texturesliderbackground>-</texturesliderbackground>
Includes.xml:        <textureslidernib>-</textureslidernib>
Includes.xml:        <textureslidernibfocus>-</textureslidernibfocus>
Includes.xml:            <lefttexture>-</lefttexture>
Includes.xml:            <righttexture>-</righttexture>
Includes.xml:            <overlaytexture>-</overlaytexture>
Includes.xml:            <lefttexture>-</lefttexture>
Includes.xml:            <righttexture>-</righttexture>
Includes.xml:            <overlaytexture>-</overlaytexture>
Includes.xml:        <texturenofocus>-</texturenofocus>
Includes.xml:        <texturefocus>-</texturefocus>
MyPrograms.xml:                    <alttexturenofocus>-</alttexturenofocus>
MyPVRGuide.xml:                                    <texture>-</texture>
SettingsScreenCalibration.xml:            <texturenofocus>-</texturenofocus>
SettingsScreenCalibration.xml:            <texturenofocus>-</texturenofocus>
SettingsScreenCalibration.xml:            <texturenofocus>-</texturenofocus>
SettingsScreenCalibration.xml:            <texturenofocus>-</texturenofocus>
