### ISSUE TITLE
skin.aeon.tajo

### ISSUE THREAD

**Issue by manfeed** [xbmc/repo-skins#197]
### Add-on details:

- **General**
  - Add-on name: Aeon TAJO
  - Add-on ID: skin.aeon.tajo
  - Version number: 1.1.5
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/manfeed/skin.aeon.tajo
  - Revision/tag: fa8123d
  - Branch: master

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by Rechi** [comment]
You are using the old language directory structure, please migrate to the new one.
see https://kodi.wiki/view/Language_support#Layout_of_the_language_folders for more info

**Comment by ronie** [comment]
thanx for submitting your skin to the kodi repo, much appreciated!

i'll take it for a test ride and report back asap.

meanwhile, here's a tool to handle the language directory structure for you:
https://forum.kodi.tv/showthread.php?tid=332789
will save you a the time of having to rename every folder manually

**Comment by ronie** [comment]
ok, done with my review, please have a look at these issues:

Could not find include file Includes_16x9.xml
1080i/Includes.xml: line 12

Could not find include file View_51_InfoWall.xml
1080i/Includes.xml: line 15

Label in <label> not translated: New Search
1080i/script-globalsearch.xml: line 1096

Label in <label> not translated: Category
1080i/script-globalsearch.xml: line 1130

Invalid texture name: -
1080i/DialogAddonInfo.xml: line 196

please remove these folders:
skin.aeon.tajo/media/resources/recordlabel
skin.aeon.tajo/media/resources/studios
those images are already provided by the resource addons

please remove this file:
skin.aeon.tajo/scripts/checkexist.py
skins can not include scripts, please provide it as a seperate addon.


in case you have any questions, or need help, just let me know :-)

**Comment by manfeed** [comment]
Thanks for your review, I’ll work on resolving the issues mentioned. However I think I’ll need your help about the little script included, checkexist.py. It’s only used as a way to check whether a theme.mp3 exists in a movie/tvshow folder and to play it when browsing. I didn’t want to force people to install another addon just for that, is there another way that you can think of? Thanks in advance.

**Comment by ronie** [comment]
> I didn’t want to force people to install another addon just for that, is there another way that you can think of?

the addon will be auto-installed if you require it in your addon.xml file,
so not much to worry about imo.
the other benefit of creating an addon for it, is other skins could make use of it to.

also, the ability to directly execute .py files will be removed in the future (as can be seen in the log).
```
2019-02-25 00:37:46.064 T:140427952920320   DEBUG: CPythonInvoker(16, special://skin/scripts/checkexist.py): the source file to load is "special://skin/scripts/checkexist.py" ("/home/ronie/.kodi/addons/skin.aeon.tajo/scripts/checkexist.py")
2019-02-25 00:37:46.064 T:140427952920320 WARNING: CPythonInvoker(16): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
```

if you need a hand creating such an addon, i'll gladly help you out.

**Comment by manfeed** [comment]
> if you need a hand creating such an addon, i'll gladly help you out.

I would appreciate it a lot, thanks in advance!

**Comment by ronie** [comment]
you can get it here:
https://gitlab.com/ronie/script.cu.lrclyrics/uploads/ffc3d76774f0f74697f22e387744c384/script.check.theme.zip

feel free to change whatever you like in the addon.

**Comment by manfeed** [comment]
Thanks! It works great! Only thing is that I noticed a small mistake in line 5 of readme.txt; I think that it should read...

<onload>RunScript(script.check.theme)</onload>

...instead of...

<onload>RunScript(special://skin/scripts/checkexist.py)</onload>

Is it going to be available through the official repository? That would be great!

I'm improving the skin taking into account the issues that you found and some new ideas, as soon as it's ready I will resend it.

Thanks again!

**Comment by ronie** [comment]
correct, i'll fix the README.
i'll make sure to add the addon to our repo at the same time as your skin.

**Comment by manfeed** [comment]
Hopefully it's fixed now...

https://github.com/manfeed/skin.aeon.tajo
commit 0b5acd8

I added to addon.xml the line...

`<import addon="script.check.theme" version="0.0.1"/>`

...is it ok?

Thanks!

**Comment by ronie** [comment]
yup, prefect.

added script.check.theme to the repo:
https://github.com/xbmc/repo-scripts/commit/faa8f2de1b0fe4c3a1c582449e55f5d968bd461a

added skin.aeon.tajo to the repo:
https://github.com/xbmc/repo-skins/commit/1ba70fba9569242c18df14d484c88a168430a2a9

thx!
