### ISSUE TITLE
skin.aeonmq8 2.8.0

### ISSUE THREAD

**Issue by MarcosQui** [xbmc/repo-skins#201]
### Add-on details:

- **General**
  - Add-on name: Aeon MQ 8
  - Add-on ID: skin.aeonmq8
  - Version number: 2.8.0
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://drive.google.com/drive/folders/0BxZQqz5XxlaDZXVEcHhVTHdtSk0?usp=sharing
  - Revision/tag: ?
  - Branch: master

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by Rechi** [comment]
### kodi-addon-checker
```
INFO: Checking add-on skin.aeonmq8
failed validating 'pt_br' with XsdPatternsFacet(['[a-z]{2,3}(_[A-Z]{2}(@\\S+)?)?']):

Reason: value doesn't match any pattern of ['[a-z]{2,3}(_[A-Z]{2}(@\\S+)?)?'].

Schema:

  <xs:pattern xmlns:xs="http://www.w3.org/2001/XMLSchema" value="[a-z]{2,3}(_[A-Z]{2}(@\S+)?)?" />

Instance:

  <summary lang="pt_br">Aeon MQ 8, melhorada, mais leve e mais poderosa do que nunca.</summary>

Path: /extension/summary[2]

failed validating 'pt_br' with XsdPatternsFacet(['[a-z]{2,3}(_[A-Z]{2}(@\\S+)?)?']):

Reason: value doesn't match any pattern of ['[a-z]{2,3}(_[A-Z]{2}(@\\S+)?)?'].

Schema:

  <xs:pattern xmlns:xs="http://www.w3.org/2001/XMLSchema" value="[a-z]{2,3}(_[A-Z]{2}(@\S+)?)?" />

Instance:

  <description lang="pt_br">A tradicional Aeon MQ chega a sua oitava edi▒▒o.[CR]Aeon MQ 8 conta com todos os recursos presentes na vers▒o anterior, no entanto, esses recursos foram otimizados afim de proporcionar uma experi▒ncia ainda melhor ao usu▒rio.[CR]Aeon MQ 8 incorpora um novo recurso chamado WIDGES FLEX▒VEIS SEGUNDA GERA▒▒O que eleva o n▒vel de customiza▒▒o como voc▒ nunca viu antes.[CR]Aeon MQ 8, voc▒ nunca viu uma skin assim.</description>

Path: /extension/description[2]

failed validating '' with XsdPatternsFacet(['\\s*([^\\s]\\s*)+']):

Reason: value doesn't match any pattern of ['\\s*([^\\s]\\s*)+'].

Schema:

  <xs:pattern xmlns:xs="http://www.w3.org/2001/XMLSchema" value="\s*([^\s]\s*)+" />

Instance:

  <source />

Path: /extension/source

failed validating '' with XsdPatternsFacet(['\\s*([^\\s]\\s*)+']):

Reason: value doesn't match any pattern of ['\\s*([^\\s]\\s*)+'].

Schema:

  <xs:pattern xmlns:xs="http://www.w3.org/2001/XMLSchema" value="\s*([^\s]\s*)+" />

Instance:

  <screenshot />

Path: /extension/assets/screenshot

ERROR: Schema validation failed for the following points: xbmc.addon.metadata
WARN: http://forum.kodi.tv/ redirects to https://forum.kodi.tv/
INFO: Image icon exists
ERROR: Icon.png should be solid. It has transparency.
INFO: Icon dimensions are fine 256x256
INFO: Image fanart exists
INFO: Fanart dimensions are fine 1920x1080
WARN: Empty image tag found for screenshot
INFO: PO files are valid
ERROR: We found 2 problems and 2 warnings, please check the logfile.
```

**Comment by MarcosQui** [comment]
a new file has been submitted to Google Drive with the fixes

**Comment by MarcosQui** [comment]
a new file has been submitted to Google Drive

**Comment by KarellenX** [comment]
A minor issue with MPAA Ratings I noticed while testing your skin.

Australian Classifications are as described here... 
http://www.classification.gov.au/Guidelines/Pages/Guidelines.aspx

Your code has this instead
```
        MPAA Australia
        <value condition="String.Contains(Container(510).ListItem.Mpaa,HU-KN)">$VAR[mpaa_path]HU_KN.png</value>
        <value condition="String.Contains(Container(510).ListItem.Mpaa,HU-12)">$VAR[mpaa_path]HU_12.png</value>
        <value condition="String.Contains(Container(510).ListItem.Mpaa,HU-16)">$VAR[mpaa_path]HU_16.png</value>
        <value condition="String.Contains(Container(510).ListItem.Mpaa,HU-18)">$VAR[mpaa_path]HU_18.png</value>
```

**Comment by MarcosQui** [comment]
In fact the flags do not correspond to Australia, but the Czech Republic. A new file has been submitted to Google Drive.

**Comment by ronie** [comment]
here's my 'please fix this' wish list:


**addon.xml**
`<disclaimer lang="en_US">Aeon MQ 8, melhorada, mais leve e mais poderosa do que nunca.</disclaimer>`
should be "pt_BR"

**variables**
Variable not defined: musicdisc_layout
- xml/ViewPoster.xml: line 159
- xml/ViewLowList.xml: line 462
- xml/ViewWide.xml: line 335

Variable not defined: gamevideoseconds
- xml/IncludesTopMenu.xml: line 2528

**fonts**
Font not defined: Font_plot (case sensitive issue)
- xml/ViewShowCase.xml: line 116
- xml/ViewShowCase.xml: line 128
- xml/ViewShowCase.xml: line 136
- xml/ViewShowCase.xml: line 999
- xml/ViewShowCase.xml: line 1203

**labels**
Label not translated: INFO[RDS.ProgStyle]
- xml/DialogPVRRadioRDSInfo.xml: line 410

Label not translated: login
- xml/LoginScreen.xml: line 23

Label not defined: 416
- xml/ViewGames.xml: line 254
- xml/ViewGames.xml: line 265
- xml/ViewGames.xml: line 276
- xml/ViewGames.xml: line 287
- xml/ViewGames.xml: line 298
- xml/ViewGames.xml: line 309

Label not defined: 161
- xml/DialogPVRRadioRDSInfo.xml: line 82
- xml/DialogPVRRadioRDSInfo.xml: line 163
- xml/DialogPVRRadioRDSInfo.xml: line 221
- xml/DialogPVRRadioRDSInfo.xml: line 247
- xml/DialogPVRRadioRDSInfo.xml: line 274
- xml/DialogPVRRadioRDSInfo.xml: line 356

Label not defined: 31329
- xml/DialogPlayerProcessInfo.xml: line 217

Label not defined: 31330
- xml/DialogPlayerProcessInfo.xml: line 224

Label not defined: 31331
- xml/DialogPlayerProcessInfo.xml: line 136
- xml/DialogPlayerProcessInfo.xml: line 145

Label not defined: 31332
- xml/DialogPlayerProcessInfo.xml: line 154

Label not defined: 31337
- xml/DialogPlayerProcessInfo.xml: line 189

Label not defined: 15057
- xml/DialogAudioDSPManager.xml: line 75

Label not defined: 15114
- xml/DialogAudioDSPManager.xml: line 76

Label not defined: 15058
- xml/DialogAudioDSPManager.xml: line 82

Label not defined: 15113
- xml/DialogAudioDSPManager.xml: line 83

Label not defined: 15059
- xml/DialogAudioDSPManager.xml: line 89

Label not defined: 15115
- xml/DialogAudioDSPManager.xml: line 90

Label not defined: 15060
- xml/DialogAudioDSPManager.xml: line 96

Label not defined: 15117
- xml/DialogAudioDSPManager.xml: line 97

Label not defined: 15061
- xml/DialogAudioDSPManager.xml: line 103

Label not defined: 15116
- xml/DialogAudioDSPManager.xml: line 104

Label not defined: 15020
- xml/DialogAudioDSPManager.xml: line 114

Label not defined: 15064
- xml/DialogAudioDSPManager.xml: line 478

Label not defined: 35500
- xml/IncludesTopMenu.xml: line 2087

**window id's**
Window ID not defined: 1141
- xml/IncludesHomeCustom.xml: line 2029
- xml/IncludesHomeCustom.xml: line 2035

Window ID not defined: 1142
- xml/IncludesHomeCustom.xml: line 2035
- xml/IncludesHomeCustom.xml: line 2029

Window ID not defined: 1143
- xml/IncludesHomeCustom.xml: line 2029
- xml/IncludesHomeCustom.xml: line 2035

Window ID not defined: 1144
- xml/IncludesHomeCustom.xml: line 2029
- xml/IncludesHomeCustom.xml: line 2035

Window ID not defined: 1145
- xml/IncludesHomeCustom.xml: line 2029
- xml/IncludesHomeCustom.xml: line 2035

Window ID not defined: 10012
- xml/Includes.xml: several lines

Window ID not defined: 10013
- xml/Includes.xml: several lines

Window ID not defined: 10014
- xml/Includes.xml: several lines

Window ID not defined: 10015
- xml/Includes.xml: several lines

Window ID not defined: 10016
- xml/Includes.xml: several lines

Window ID not defined: 10017
- xml/Includes.xml: several lines

Window ID not defined: 10018
- xml/Includes.xml: several lines

Window ID not defined: 10019
- xml/Includes.xml: several lines

Window ID not defined: 10021
- xml/Includes.xml: several lines

Window ID not defined: 629
- xml/customSubMenuSmart.xml: line 92

Window ID not defined: 1153
- xml/ViewGames.xml: line 1112
- xml/ViewGames.xml: line 615
- xml/MyVideoPlaylist.xml: line 140
- xml/MyPics.xml: line 77
- xml/ViewShowArt.xml: line 42
- xml/ViewShowArt.xml: line 217
- xml/ViewBannerInfo.xml: line 112
- xml/ViewPoster.xml: line 42
- xml/MyVideoNav.xml: line 153
- xml/MyVideoNav.xml: line 185
- xml/MyVideoNav.xml: line 290
- xml/Includes.xml: line 1446
- xml/ViewRightListTV.xml: line 210
- xml/MyMusicNav.xml: line 71
- xml/MyMusicNav.xml: line 110
- xml/ViewLowList.xml: line 71
- xml/ViewLowList.xml: line 154
- xml/ViewLowList.xml: line 226
- xml/ViewLowList.xml: line 85
- xml/ViewLowList.xml: line 414
- xml/ViewMyViewType1.xml: line 22
- xml/ViewGlassList.xml: line 216
- xml/ViewShowCase.xml: line 927
- xml/ViewWide.xml: line 307
- xml/ViewRightList.xml: line 231
- xml/ViewMultiplex.xml: line 59
- xml/ViewMultiplex.xml: line 276
- xml/script-NextAired-TVGuide.xml: line 909
- xml/defaults.xml: line 161
- xml/IncludesTopMenu.xml: line 2529

**brackets**
Brackets do not match: 
string.isequal(container(9000).listitem.property(widgets),tvshow.unwatched
- xml/IncludesWidgets.xml: line 1089

**Comment by MarcosQui** [comment]
A new file has been submitted to Google Drive.

**Comment by ronie** [comment]
thx for the quick fixes!

skin has been added to the leia repo:
https://github.com/xbmc/repo-skins/commit/75726b09a9b9e52a5bb4d95cd6aeb7e91f792d64
