### ISSUE TITLE
skin.bello.7 v7.0.0

### ISSUE THREAD

**Issue by Nessus85100** [xbmc/repo-skins#210]
### Add-on details:
- **General**
  - Add-on name: Bello 7
  - Add-on ID: skin.bello.7
  - Version number: 7.0.0
  - Kodi/repository version: Leia
- **Code location**
  - URL: https://github.com/Nessus85100/skin.bello.7
  - Revision/tag: Latest
  - Branch: Master

### Description of changes:
https://github.com/Nessus85100/skin.bello.7/commits/master

**Comment by ronie** [comment]
**addon.xml**
please use http**s**://forum.kodi.tv in your `<forum>` tag

great, thanx for making your skin compatible with Kodi Leia :-)

i've reviewed Bello.7 and found a few things for you to look at:


**MAC Line Endings detected, please use Unix stye EOL's**
- DialogPlayerProcessInfo.xml
- VideoFullScreen.xml


**Font not defined: FontSize_10**
- IncludesHome.xml: line 828


**Label not defined: 416**
- IncludesNotifications.xml: line 239


**Label not defined: 31189**
- Custom_ManageDialog.xml: line 142


**Window ID not defined: 110**
- DialogKeyboard.xml: line 146


**unmatched parentheses in string.startswith(listitem.mpaa,rated: pg**
- IncludesFlags.xml


**invalid include: skinshortcuts-template-widget**
- IncludesHomeWidgets.xml


**could not find texture 'overlays/unwatched/list/UnWatched.png' (case sensitive issue)**
- ViewsVideos.xml


**could not find texture 'thumbs/DefaultVideo.png/folderback_episode_tp.png'**
- IncludesViews.xml


**could not find texture 'thumbs/DefaultVideo.png/folderback_poster_big_tp.png'**
- ViewsVideos.xml


**could not find texture 'windows/pvr/clock_progress/back.png'**
- IncludesMenus.xml
- ViewsPVR.xml

**Comment by Nessus85100** [comment]
Hi @ronie 
Thanks for the quick answer

All fixed in the latest commit, except of these:

>  invalid include: skinshortcuts-template-widget
    IncludesHomeWidgets.xml

This is an include created by the skinshortcuts script in script-skinshortcuts-includes.xml


> could not find texture 'thumbs/DefaultVideo.png/folderback_episode_tp.png'
    IncludesViews.xml

> could not find texture 'thumbs/DefaultVideo.png/folderback_poster_big_tp.png'
    ViewsVideos.xml

There is no such path `thumbs/DefaultVideo.png/` defined in my code in any xml file.

Let me know if everything are ok now.

Cheers
Nessus

**Comment by ronie** [comment]
ah, i never really checked how that skinshortcuts exactly works, so yeah you can ignore that one.

as for the other issue, you're constructing that path in your code like this:
`<value>$INFO[ListItem.ActualIcon,thumbs/,/folderback_episode_tp.png]</value>`

it's not the end of the world, but perhaps you can keep an eye on it..
you'll get warnings in the log like this:
`[Warning] CGUITextureManager::GetTexturePath: could not find texture 'thumbs/DefaultFolder.png/folderback_poster_big_tp.png'`

anyway... Bello.7 has been added to the leia repo, thx!
https://github.com/xbmc/repo-skins/commit/03f4b995187c288fbf44dba1c2d811b409dae1ce
