### ISSUE TITLE
[New skin] skin.omni

### ISSUE THREAD

**Issue by braz96** [xbmc/repo-skins#22]
### Add-on details:

- **General**
  - Add-on name: OMNI
  - Add-on ID: skin.omni
  - Version number: 1.0.0
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/braz96/skin.omni
  - Revision/tag: ea2f599f838788b30f2ef469c5c5d8837d2dad2c
  - Branch: master

### Description of changes:

This is a new skin based on Mimic. Code checked using Phil65s SublimeText plugin.

Do skin submissions need to be in a single commit? If so, are there any guidelines for how to do this while maintaining history, etc? Thanks!

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by braz96** [comment]
If/when this gets added to the repo, there's a thread in WIP skins that can be moved to skin support.

http://forum.kodi.tv/showthread.php?tid=303540

**Comment by ronie** [comment]
> Do skin submissions need to be in a single commit?

nope, that only applies if you would submit a PR to the skin repo.

**Comment by ronie** [comment]
@braz96 been taking omni for a ride and came across these issues, mind having a look:


the license tag in addon.xml does not match with the includes License file (GPLv2 vs CC BY-NC-SA)


please remove:
- media/Default.xbt


these windows are referenced in Variables.xml, but we don't have those:
- Window.IsActive(musicvideos)
- Window.IsActive(programsettings)


these images are reference by the shortcuts/*.DATA.xml files, but are missing?
- UpdateVideoLibrary.png
- UpdateMusicLibrary.png


script-cu-lrclyrics-main.xml is causing errors in the log
- ERROR: Control 101 in window 13000 has been asked to focus, but it can't
(remove the `<defaultcontrol>` definition)

**Comment by braz96** [comment]
Should all be fixed now, thanks for catching those @ronie. Updated the first post with the new revision.

**Comment by ronie** [comment]
great, thanx!

just one more thing i spotted in script-cu-lrclyrics-main.xml,
please don't set the visibility of list control id="110" to false.

to 'hide' the list, you could specify a transparent textcolor for the label controls
(at least that's what aeon nox uses)

or perhaps removing the label controls and use an empty item/focused layout might work as well...

**Comment by braz96** [comment]
New revision added to the first post. Also fixed a few other issues like the videoplaylist window. Cheers!

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-skins/commit/3b4d0dba3ece94ae046b62b68317829456362509
