### ISSUE TITLE
[Update] skin.aeon.nox.silvo v7.9.2 + [Update] skin.aeon.nox.silvo v7.0.6

### ISSUE THREAD

**Issue by mikesilvo164** [xbmc/repo-skins#259]
### Add-on details:
- **General**
  - Add-on name: Aeon Nox: SiLVO
  - Add-on ID: skin.aeon.nox.silvo
  - Version number: 7.9.2
  - Kodi/repository version: Matrix

- **Code location**
  - URL: https://github.com/mikesilvo164/Aeon-Nox-SiLVO
  - Revision/tag: latest please
  - Branch: master
  - Kodi/repository version: Matrix

### Add-on details:
- **General**
  - Add-on name: Aeon Nox: SiLVO
  - Add-on ID: skin.aeon.nox.silvo
  - Version number: 7.0.6
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/mikesilvo164/Aeon-Nox-SiLVO
  - Revision/tag: latest please
  - Branch: leia
  - Kodi/repository version: Leia

### Description of changes:
- Fix menu reverting to default

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by mikesilvo164** [comment]
Not sure if you will get my post in the other issue so opened a new one:
From other post:
```
@ronie Can you please pull latest from both branches ASAP. 
A change I made to the darn overrides.xml file is resetting menus 
and I'd like to get it fixed before the complaints come pouring in.

Thanks and sorry for the mess up.
```

**Comment by ronie** [comment]
ok, both updated:

matrix:
https://github.com/xbmc/repo-skins/commit/423be174d28f6cf423305b0f3fc7b97d590eee39

leia:
https://github.com/xbmc/repo-skins/commit/7115f93e1b74fcf03a97bdaced759a134c2c4090

**Comment by mikesilvo164** [comment]
Thanks ronie 😃
