### ISSUE TITLE
[update] skin.pellucid 1.0.4

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#27]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 1.0.4
- Kodi/repository version: Krypton
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: 00cdbebe4bf9d562e439a8527138dad371b58128
- Branch: master

### Description of changes:
- Minor bug fixes and tweaks
- [NEW] User option to remove weather data from homescreen

### Checklist:
- [ x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [ x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
all your files are marked as executable, could you please fix that?

the rest looks good to me.

**Comment by chrisbevan** [comment]
Thanks Ronie. Permissions fixed in commit 610a7bbd8facdd015e20fa5138cbbb9060cb1402

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/de7deed6c89d4da69669a5c2cb08531ba0dcff9f
