### ISSUE TITLE
[release] skin.quartz 5.19.0

### ISSUE THREAD

**Issue by nonJon** [xbmc/repo-skins#293]
### Add-on details:

- **General**
  - Add-on name:  Quartz
  - Add-on ID: skin.quartz
  - Version number: 5.19.0
  - Kodi/repository version: matrix

- **Code location**
  - URL:  https://github.com/nonJon/skin.quartz
  - Revision/tag:  latest
  - Branch: master

### Description of changes:

v19 compat

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
added to the matrix repo, thx!
https://github.com/xbmc/repo-skins/commit/42d9a6f72b1071b4a942f7eb1491e9cdc41849e6
