### ISSUE TITLE
[Update] skin.mimic 5.0.3

### ISSUE THREAD

**Issue by braz96** [xbmc/repo-skins#30]
### Add-on details:

- **General**
  - Add-on name: Mimic skin
  - Add-on ID: skin.mimic
  - Version number: 5.0.3
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/braz96/skin.mimic
  - Revision/tag: 171b0d65c2de0574ee16a8be522a817d97c4c210
  - Branch: master

### Description of changes:

- Adjust views for video addons.
- Fix watched/unwatched indicator settings.
- Misc bug fixes.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/196abc81c8e56e676a664b56abe8edd57a851f7b
