### ISSUE TITLE
[UPDATE] Skin.pellucid V2.2.0

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#302]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 2.2.0
- Kodi/repository version: Leia
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: 8f0930b562fbfcc923e84bfe0e50f8b611ebcae6
- Branch: master

### Description of changes:
- Various tweaks and updates

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
thanx for the update, i did come across this issue:

Window ID not defined: 1105
1080i/custom_musicPlayerFullscreen.xml: line 197

also, could you check if this folder is really needed:
skin.pellucid/colors/fonts

**Comment by chrisbevan** [comment]
Thanks Ronie, sorry I didn't spot those. Fixed in c2e4bbed815800f468117fd01529533a56af2de6

**Comment by ronie** [comment]
great, thanx!

just one more thing that i only noticed now:
your addon version is set to `2.2` instead of `2.2.0`

**Comment by chrisbevan** [comment]
Bah. Fixed: 970e4458dcb42d26a25adc6e789b0221425aafd6

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/a8b8c17a68f74596751a955fa7721075cad101bd
