### ISSUE TITLE
[Matrix] skin.unity

### ISSUE THREAD

**Issue by bumpaneer** [xbmc/repo-skins#318]
> ### Add-on details:
> * **General**
>   
>   * Add-on name: Unity
>   * Add-on ID: skin.unity
>   * Version number: 0.19.0
>   * Kodi/repository version: Matrix
> 
> * **Code location**
>   
>   * URL: https://github.com/bumpaneer/skin.unity
>   * Revision/tag: c2f0538ff8243d36c238184857a45f9259d6c045
>   * Branch: master
> 
> ### Description of changes:
> * Initial Matrix version
> 
> ### Checklist:
> * [x]  My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.
> * [x]  I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
> * [x]  Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
thanx for submitting Unity to the Matrix repo !

there's one small issue for you to fix:
Error in skin.unity/xml/DialogVideoInfo.xml:
 Double hyphen within comment, line 423, column 8 (DialogVideoInfo.xml, line 423)

(a comment within a comment is not valid xml)

**Comment by bumpaneer** [comment]
Thanks for the catch ronie.

Fixed in d0c3565728b86eb410c02e051fccb295cec3ce5c
https://github.com/bumpaneer/skin.unity/commit/d0c3565728b86eb410c02e051fccb295cec3ce5c

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-skins/commit/9e13fbfeafa5af16b9c6e3b13dfb447ea200a2ee
