### ISSUE TITLE
[UPDATE] Skin.pellucid V3

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#326]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 3
- Kodi/repository version: Matrix
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: 8127441df21293684827031f3c76cb66c532635b
- Branch: master

### Description of changes:
- Updated to V19 Matrix

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
looks good to me, only the version number looks odd to me...
could you please change it to a x.y.z format instead of just '3' ? ;-)

**Comment by chrisbevan** [comment]
Thanks Ronie - fixed in b0586f13587ca8afe038d14db4eded8f5b336661

Chris.

**Comment by ronie** [comment]
added to the matrix repo, thx!
https://github.com/xbmc/repo-skins/commit/e358d54c0625b6660179602d61f5526aa5dbc896
