### ISSUE TITLE
skin.bello.8

### ISSUE THREAD

**Issue by Nessus85100** [xbmc/repo-skins#336]
### Add-on details:
- **General**
  - Add-on name: Bello 8
  - Add-on ID: skin.bello.8
  - Version number: 8.0.0
  - Kodi/repository version: Matrix
- **Code location**
  - URL: https://github.com/Nessus85100/skin.bello.8
  - Revision/tag: Latest
  - Branch: Master

### Description of changes:
https://github.com/Nessus85100/skin.bello.8/commits/master

**Comment by ronie** [comment]
thanx for updating the Bello skin to Kdi 19!

there's a few things that require your attention:

Please remove these files:
Edit3.xml
EXPRESSIONS-INFODIALOGS.XML


Error in VideoFullScreen.xml:
Double hyphen within comment, line 234, column 6 (VideoFullScreen.xml, line 234)



Include not defined: TMDBInfo_OpenCloseAnimation
custom-1128-test.xml: line 20

Include not defined: InfoDialogsListHeaderFooter
custom-1128-test.xml: line 405

Include not defined: InfoDialogsListHeaderFooter
custom-1128-test.xml: line 436

Include not defined: InfoDialogsListHeaderFooter
custom-1128-test.xml: line 458

Include not defined: InfoDialogsListHeaderFooter
custom-1128-test.xml: line 490

Include not defined: InfoDialogsListHeaderFooter
custom-1128-test.xml: line 512

Include not defined: TMDBInfo_OpenCloseAnimation
custom-1128-test.xml: line 549


Variable not defined: ActorGenderIcon
custom-1128-test.xml: line 76

Variable not defined: AgeAndDeathDateLabel
custom-1128-test.xml: line 102

Variable not defined: ToggleIconYouTube
custom-1128-test.xml: line 380

Variable not defined: StatusSmartishWidgets
SkinSettings.xml: line 521

Variable not defined: StatusT9Search
SkinSettings.xml: line 544

Variable not defined: StatusTVShowNextAired
SkinSettings.xml: line 567

Variable not defined: StatusArtworkBeef
SkinSettings.xml: line 590

Variable not defined: StatusIMDBUpdate
SkinSettings.xml: line 597


Label not defined: 32299
Custom_Search.xml: line 203


invalid control type: "textbox...."
DialogVideoInfo.xml: line 1748



Brackets do not match: !String.Contains(Control.GetLabel(1001),$LOCALIZE[16105]) + !Skin.HasSetting(DisableQuickNav) + ![Window.IsVisible(LoginScreen) | Window.IsActive(PlayerControls) | Window.IsActive(favourites) | Window.IsActive(script-globalsearch.xml)) | Window.IsActive(fullscreenvideo) | Window.IsActive(videobookmarks) | Window.IsActive(visualisation)]
IncludesMenus.xml: line 276

**Comment by Nessus85100** [comment]
Thanks @ronie 
All not defined variables are commented and disabled. All the others are fixed... i hope!.

https://github.com/Nessus85100/skin.bello.8/commit/2b02236553f091e8d1d3acc47115137504481b1c

Cheers
Nessus

**Comment by ronie** [comment]
added to the matrix repo, thx!
https://github.com/xbmc/repo-skins/commit/234b6904e7ef5ae8581bd25d053936f3f47efaed

**Comment by Nessus85100** [comment]
Hey @ronie... just a friendly bump since it's been a week since this it closed.

Cheers
Nessus

**Comment by ronie** [comment]
hi @Nessus85100 not sure what you mean :-)
your skin was added last week to the repo, did i miss something?

**Comment by Nessus85100** [comment]
@ronie well... the folder [here ](http://mirrors.xbmc.org/addons/matrix/skin.bello.8/)is empty and if you try to add the skin in Kodi through official repo, Bello 8 is not available... 

![image](https://user-images.githubusercontent.com/1375649/121067436-b98d3c80-c7d3-11eb-88e4-5e8af90b0588.png)


Also there is the thing of renaming the Bello 7 thread to Bello 8.

**Comment by ronie** [comment]
@Nessus85100 

the problem appears to be a typo in this filename:
https://github.com/Nessus85100/skin.bello.8/blob/master/resources/screensho-01.jpg

if you could fix that and do a version bump in addon.xml, we should be good to go.

i'll handle the renaming on the forum right away..

**Comment by Nessus85100** [comment]
Sorry @ronie... fixed now 

https://github.com/Nessus85100/skin.bello.8/commit/1a59457ff1c1e519902184a8dd4ecb153c0ef602

**Comment by ronie** [comment]
thx, added.
https://github.com/xbmc/repo-skins/commit/d07f15db3a05c19d11467d6df2a981bbc7867a0f
