### ISSUE TITLE
[UPDATE] skin.ftv

### ISSUE THREAD

**Issue by Hitcher** [xbmc/repo-skins#340]
### Add-on details:

- **General**
  - Add-on name: fTV
  - Add-on ID: skin.ftv
  - Version number: v7.1.2

- **Code location**
  - URL: https://github.com/HitcherUK/skin.ftv
  - Branch: Master

### Description of changes:

Fix music bugs

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
thx! could you have a look at these issues please:

found BOM. File: script-embuary-image.xml

found BOM. File: script-embuary-video.xml

Windows Line Endings detected in script-skinshortcuts-includes.xml

Variable not defined: RatingContent
script-globalsearch.xml: line 13

**Comment by Hitcher** [comment]
Should all be good in v7.1.2.

Thanks.

**Comment by ronie** [comment]
looks good to me, thx!
https://github.com/xbmc/repo-skins/commit/dd18aee7dccaebbd01a4b74f3be4d661f43d255d
