### ISSUE TITLE
skin.arctic.zephyr.mod

### ISSUE THREAD

**Issue by beatmasterRS** [xbmc/repo-skins#341]
### Add-on details:

- **General**
  - Add-on name: Arctic: Zephyr - Reloaded
  - Add-on ID: skin.arctic.zephyr.mod
  - Version number: 1.1.55
  - Kodi/repository version: Matrix

- **Code location**
  - URL: https://github.com/beatmasterRS/skin.arctic.zephyr.mod
  - Revision/tag: latest
  - Branch: official

### Description of changes:

All changes, i have made: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/official/changelog.txt

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
thanx for submitting your skin to the addon repo!
nice to see you took the time to revive the arctic zephyr skin.

as with all new skin submission, there will be a few things to fix before we can merge it into our repository.

i had a look at the skin code and came across these issues:

please limit the number of screenshots in the resources folder to 10
(and update your addon.xml to also include max 10 screenshots)

Label not defined: 161
1080i/Includes.xml: line 1231
1080i/Includes.xml: line 1250
1080i/Includes_Home.xml: line 1679
1080i/Includes_Home.xml: line 1756
1080i/Includes_Home.xml: line 1846
1080i/Includes_Home.xml: line 1973
1080i/Includes_Home.xml: line 2044
1080i/Includes_Home.xml: line 2128
1080i/Includes_Home.xml: line 2212
1080i/Includes_Home.xml: line 2283
1080i/Includes_Home.xml: line 2367
1080i/Includes_Home.xml: line 2953
1080i/Includes_Home.xml: line 3037
1080i/Includes_Home.xml: line 3121
1080i/Includes_Home.xml: line 4149
1080i/Includes_Home.xml: line 4253
1080i/Includes_Home.xml: line 4365
1080i/Includes_Home.xml: line 4469
1080i/MyWeather.xml: line 154
1080i/MyWeather.xml: line 173
1080i/MyWeather.xml: line 247
1080i/MyWeather.xml: line 266
1080i/MyWeather.xml: line 340
1080i/MyWeather.xml: line 359
1080i/MyWeather.xml: line 433
1080i/MyWeather.xml: line 452
1080i/MyWeather.xml: line 526
1080i/MyWeather.xml: line 545
1080i/MyWeather.xml: line 619
1080i/MyWeather.xml: line 638
1080i/MyWeather.xml: line 943
1080i/MyWeather.xml: line 962
1080i/MyWeather.xml: line 1036
1080i/MyWeather.xml: line 1055
1080i/MyWeather.xml: line 1129
1080i/MyWeather.xml: line 1148
1080i/MyWeather.xml: line 1222
1080i/MyWeather.xml: line 1241
1080i/MyWeather.xml: line 1315
1080i/MyWeather.xml: line 1334
1080i/MyWeather.xml: line 1408
1080i/MyWeather.xml: line 1427

Label not defined: 32297
1080i/script-globalsearch.xml: line 66

Label not defined: 32299
1080i/script-globalsearch.xml: line 82

Window ID not defined: 1132
1080i/Includes.xml: line 1485
1080i/Includes.xml: line 1501

Window ID not defined: 1103
1080i/Includes_Furniture.xml: line 2969
1080i/Includes_Furniture.xml: line 3065
1080i/Includes_Furniture.xml: line 3065
1080i/Includes_Furniture.xml: line 3066
1080i/Includes_Furniture.xml: line 3066
1080i/Includes_Furniture.xml: line 3067

Invalid color for colordiffuse: Black
1080i/Includes.xml: line 467

Invalid color for colordiffuse: VAR[OSDPanelWhite70]
1080i/MusicOSD.xml: line 347

Missing texture: thumbs/thumb_mask.png
View_501_Modern_Fanart.xml: line 293
View_501_Modern_Fanart.xml: line 302
View_507_Fanart.xml: line 452
View_507_Fanart.xml: line 460


should you have any questions, or need help, just let me know!

**Comment by beatmasterRS** [comment]
I was always fan on Artic Zephyr, so i have tried to improve it over the years. So thanks a lot for looking into it. :)

I have fixed all the errors, you have mentioned:

Reduced Screenshots: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/0d7807510d6bedeb00308d4a29508b7e63e651b7
Fixed errors in code: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/9c9fd7510e594c39753c658a6d719165f529afac

**Comment by ronie** [comment]
thanx for the quick fixes!

added to the matrix repo: 
https://github.com/xbmc/repo-skins/commit/d351c40a1385a46130f92b55ad3641114dd3d938

**Comment by jurialmunkey** [comment]
@beatmasterRS - First up, congrats on inclusion. Great to see this in the official repo.

@ronie - I would've appreciated a ping either here or on slack before this was accepted. I know I haven't been around much of late due to work commitments but I am still around! (and apologies if you did ping me somewhere and I didn't see). 

I've got no issues with this mod being included but I'd like to see it made clear that it is a mod of the original and not a continuation - especially since Arctic Horizon will make it onto official repo soon now that I've got a bit more free time and I have also slowly been working on Arctic Zephyr 3 privately.

A name change ala Aeon Nox from Aeon (and now Aeon Tajo from Nox) would've been preferred, but that option might've flown now. Failing that, I'd like at least the summary and description in `addon.xml` to mention that it is a mod ala "Aeon Nox: SiLVO" (e.g. "An Arctic Zephyr Mod by Beatmasters. Original skin by jurialmunkey" or something along those lines)

**Comment by beatmasterRS** [comment]
Sorry, I didn't mean to cause any trouble. Just to be clear about the `addon.xml`. It's not like there is no mention of the original author and what skin A:Z - R is based on:

>>`<description lang="en">Arctic: Zephyr - Reloaded is based on the third iteration of the Arctic skin created by jurialmunkey. Arctic focuses on being simple, clean and minimalistic with a light spin.</description>`

>>`<addon id="skin.arctic.zephyr.mod" version="1.1.55" name="Arctic: Zephyr - Reloaded" provider-name="jurialmunkey, beatmasterrs">`

And of course, I'll edit the summary accordingly and mention the original author again there as well and what A: Z - R is based on. Description I will also change to make it even clearer.

**Comment by jurialmunkey** [comment]
No, no trouble at all! Sorry, didn't mean to come across as being harsh or anything like that.

Description is fine as it is. I think I just saw the last part and thought it was unchanged. I was more meaning the summary anyway - just something for when someone is installing via dialogselect that makes it clear that it is a Mod rather than AZ3 to avoid any confusion down the line.

**Comment by beatmasterRS** [comment]
Sorry, I had misunderstood that a bit. I have still adapted the description and summary something :)

**Comment by ronie** [comment]
my apologies @jurialmunkey 
i'm usually very careful before deciding if a skin mod is allowed into the repo, which includes consulting other team skinners and contacting the original author.

i didn't follow that procedure with arctic.zephyr is i (wrongly) considered it to be abandoned,
i.e. the last update we got was over 3.5 years ago for krypton / forum support thread archived.

it's a lesson learned for me and i'll be more careful next time.
