### ISSUE TITLE
[skin.mimic.lr] v7.0.2

### ISSUE THREAD

**Issue by randallspicher** [xbmc/repo-skins#356]
### Add-on details:

- **General**
  - Add-on name: Mimic-LR
  - Add-on ID:skin.mimic.lr
  - Version number:7.0.2
  - Kodi/repository version:Matrix

- **Code location**
  - URL: https://github.com/randallspicher/skin.mimic.lr
  - Revision/tag: adfe7a7376262c63b4060a93f5c74629430f2337
  - Branch: Matrix

### Description of changes:
The original Mimic skin has been "archived" for some time now, and the original maintainer has moved on to other things.
Mimic-LR is a fork (of a fork) which is still being maintained, and updated for Matrix.  

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
nice to see another skin being recovered from the past :-)

as with all first-time submissions to the skin repo, it will need a bit of clean up before i can be merged.

i had a look at the code and came up with this list:

### Addon.xml
- please change the `addon id` to skin.mimic.lr
- please change the `addon name ` to Mimic-LR
- skins are not allowed to include python scripts, so please remove the `kodi.context.item` extention point and remove the scripts folder. if your skin needs any specific scripts, please submit them as separate addons to the addon repo.
- please add a fanart image for your skin
- also, include a few screenshots of your skin (max. 10)


### Code checks
Include file missing: Includes_WeatherObjects.xml
1080i/includes.xml: line 5

Include not defined: OnBackInclude
1080i/View_902_KeibertzPlus.xml: line 46

Include not defined: OnBackInclude
1080i/View_909_Sauna.xml: line 49

Variable not defined: PlayerSourceFlagVar
1080i/DialogFullScreenInfo.xml: line 60

Variable not defined: Art2LabelVar
1080i/includes.xml: line 240

Variable not defined: Art2LabelVar
1080i/includes.xml: line 254

Variable not defined: PlayerSourceFlagVar
1080i/DialogFullScreenInfo.xml: line 60/61

Control / Item ID not defined: 313
1080i/DialogKeyboard.xml: line 453

Control / Item ID not defined: 313
1080i/includes.xml: line 835

Control / Item ID not defined: 607
1080i/variables.xml: line 477

invalid attribute for <texture>: xdiffuse
1080i/MyWeather-includes-Maps.xml: line 45

invalid attribute for <texture>: xdiffuse
1080i/MyWeather-includes-Maps.xml: line 53

invalid attribute for <texture>: xdiffuse
1080i/MyWeather-includes-Maps.xml: line 62

invalid attribute for <texture>: xdiffuse
1080i/MyWeather-includes-Maps.xml: line 70

invalid attribute for <texture>: xdiffuse
1080i/MyWeather-includes-Maps.xml: line 98

invalid attribute for <texture>: xdiffuse
1080i/MyWeather-includes-Maps.xml: line 106

invalid attribute for <texture>: xdiffuse
1080i/MyWeather-includes-Maps.xml: line 123

invalid attribute for <texture>: xdiffuse
1080i/MyWeather-includes-Maps.xml: line 131


### The labels do not exist in the Kodi language file
Label not defined: 161
1080i/script-script.extendedinfo-DialogVideoInfo.xml: line 1010

Label not defined: 161
1080i/script-script.extendedinfo-DialogVideoInfo.xml: line 211

Label not defined: 161
1080i/script-script.extendedinfo-DialogInfo.xml: line 912

Label not defined: 161
1080i/script-script.extendedinfo-DialogInfo.xml: line 90

Label not defined: 161
1080i/script-script.extendedinfo-DialogInfo.xml: line 94

Label not defined: 161
1080i/script-script.extendedinfo-DialogInfo.xml: line 99

Label not defined: 161
1080i/script-script.extendedinfo-DialogInfo.xml: line 104

Label not defined: 161
1080i/script-script.extendedinfo-DialogInfo.xml: line 108

Label not defined: 161
1080i/script-script.extendedinfo-DialogInfo.xml: line 113

Label not defined: 161
1080i/script-script.extendedinfo-DialogInfo.xml: line 117

Label not defined: 161
1080i/script-script.extendedinfo-DialogInfo.xml: line 141

Label not defined: 161
1080i/DialogPVRInfo.xml: line 103

Label not defined: 15064
1080i/DialogAudioDSPManager.xml: line 136

Label not defined: 15088
1080i/includes.xml: line 1545


### The labels do not exist in the skin language file
Label not defined: 31113
1080i/custom_1107_SearchDialog.xml: line 21

Label not defined: 31145
1080i/custom_1107_SearchDialog.xml: line 27

**Comment by ronie** [comment]
...continuing with a list of labels that should be localized:

Label in <label2> not translated: Certification:
1080i/DialogVideoInfo.xml: line 107

Label in <label2> not translated: Resolution:
1080i/DialogVideoInfo.xml: line 188

Label in <label2> not translated: Video Codec:
1080i/DialogVideoInfo.xml: line 198

Label in <label2> not translated: Video Aspect:
1080i/DialogVideoInfo.xml: line 203

Label in <label2> not translated: Audio Codec:
1080i/DialogVideoInfo.xml: line 208

Label in <label2> not translated: Audio Channels:
1080i/DialogVideoInfo.xml: line 213

Label in <label> not translated: Window art
1080i/View_902_KeibertzPlus.xml: line 75

Label in <label> not translated: Bright icons
1080i/View_902_KeibertzPlus.xml: line 83

Label in <label> not translated: Disable zoom
1080i/View_902_KeibertzPlus.xml: line 90

Label in <label> not translated: Hide reflections
1080i/View_902_KeibertzPlus.xml: line 97

Label in <label> not translated: Hide labels
1080i/View_902_KeibertzPlus.xml: line 104

Label in <label> not translated: Window art
1080i/View_902_KeibertzPlus.xml: line 111

Label in <label> not translated: Bright icons
1080i/View_902_KeibertzPlus.xml: line 119

Label in <label> not translated: Disable zoom
1080i/View_902_KeibertzPlus.xml: line 126

Label in <label> not translated: Hide reflections
1080i/View_902_KeibertzPlus.xml: line 133

Label in <label> not translated: Hide labels
1080i/View_902_KeibertzPlus.xml: line 140

Label in <label> not translated: Window art
1080i/View_902_KeibertzPlus.xml: line 147

Label in <label> not translated: Bright icons
1080i/View_902_KeibertzPlus.xml: line 155

Label in <label> not translated: Disable zoom
1080i/View_902_KeibertzPlus.xml: line 162

Label in <label> not translated: Hide reflections
1080i/View_902_KeibertzPlus.xml: line 169

Label in <label> not translated: Hide labels
1080i/View_902_KeibertzPlus.xml: line 176

Label in <label> not translated: Trailers
1080i/View_902_KeibertzPlus.xml: line 183

Label in <label> not translated: Layout
1080i/View_909_Sauna.xml: line 521

Label in <label> not translated: Window art
1080i/View_909_Sauna.xml: line 529

Label in <label> not translated: Bright icons
1080i/View_909_Sauna.xml: line 545

Label in <label> not translated: Disable zoom
1080i/View_909_Sauna.xml: line 552

Label in <label> not translated: Trailers
1080i/View_909_Sauna.xml: line 559

Label in <label> not translated: Layout
1080i/View_900_Arcade.xml: line 1063

Label in <label> not translated: Window art
1080i/View_900_Arcade.xml: line 1071

Label in <label> not translated: Bright icons
1080i/View_900_Arcade.xml: line 1080

Label in <label> not translated: Hide star ratings
1080i/View_900_Arcade.xml: line 1087

Label in <label> not translated: Hide studio flags
1080i/View_900_Arcade.xml: line 1095

Label in <label> not translated: Layout
1080i/View_900_Arcade.xml: line 1103

Label in <label> not translated: Window art
1080i/View_900_Arcade.xml: line 1111

Label in <label> not translated: Bright icons
1080i/View_900_Arcade.xml: line 1120

Label in <label> not translated: Hide star ratings
1080i/View_900_Arcade.xml: line 1127

Label in <label> not translated: Hide studio flags
1080i/View_900_Arcade.xml: line 1135

Label in <label> not translated: Layout
1080i/View_900_Arcade.xml: line 1143

Label in <label> not translated: Bright icons
1080i/View_900_Arcade.xml: line 1151

Label in <label> not translated: Hide labels
1080i/View_900_Arcade.xml: line 1158

Label in <label> not translated: Hide star ratings
1080i/View_900_Arcade.xml: line 1165

Label in <label> not translated: Hide studio flags
1080i/View_900_Arcade.xml: line 1173

Label in <label> not translated: Layout
1080i/View_900_Arcade.xml: line 1181

Label in <label> not translated: Window art
1080i/View_900_Arcade.xml: line 1189

Label in <label> not translated: Bright icons
1080i/View_900_Arcade.xml: line 1198

Label in <label> not translated: Trailers
1080i/View_900_Arcade.xml: line 1205

Label in <label> not translated: Hide star ratings
1080i/View_900_Arcade.xml: line 1214

Label in <label> not translated: Hide studio flags
1080i/View_900_Arcade.xml: line 1223

Label in <label> not translated: Seasons
1080i/View_900_Arcade.xml: line 1380

Label in <label> not translated: Episodes
1080i/View_900_Arcade.xml: line 1402

Label in <label> not translated: Watched
1080i/View_900_Arcade.xml: line 1424

Label in <label> not translated: Unwatched
1080i/View_900_Arcade.xml: line 1446

Label in <label> not translated: Seasons
1080i/View_900_Arcade.xml: line 1772

Label in <label> not translated: Episodes
1080i/View_900_Arcade.xml: line 1794

Label in <label> not translated: Watched
1080i/View_900_Arcade.xml: line 1816

Label in <label> not translated: Unwatched
1080i/View_900_Arcade.xml: line 1838

Label in <label> not translated: Year: [COLOR=white]$INFO[ListItem.Year][/COLOR]   [COLOR=grey]•[/COLOR]   Genre:  [COLOR=white]$INFO[ListItem.Genre][/COLOR]   [COLOR=grey]•[/COLOR]   Rating:  [COLOR=white]$INFO[ListItem.Rating][/COLOR]
1080i/View_900_Arcade.xml: line 2293

Label in <label> not translated: Layout
1080i/View_903_Coverflow.xml: line 324

Label in <label> not translated: Bright icons
1080i/View_903_Coverflow.xml: line 332

Label in <label> not translated: Layout
1080i/View_903_Coverflow.xml: line 339

Label in <label> not translated: Bright icons
1080i/View_903_Coverflow.xml: line 347

Label in <label> not translated: Bright icons
1080i/View_903_Coverflow.xml: line 354

Label in <label> not translated: Layout
1080i/View_903_Coverflow.xml: line 361

Label in <label> not translated: Bright icons
1080i/View_903_Coverflow.xml: line 369

**Comment by ronie** [comment]
last but not least, if you have any questions or need help, please let me know!

**Comment by randallspicher** [comment]
I've made updates, and tagged as 7.0.1 release (and updated the issue to reflect that).

The "Codacy" thing mentioned in the boiler plate seems to have stopped working at Krypton...  what do you use now for code checks?  Is there any way I could run that against the code myself?

**Comment by ronie** [comment]
thanx for the prompt fixes!

for my skin checks i use a few python scripts which are part of this text editor plugin:
https://forum.kodi.tv/showthread.php?tid=221682
https://github.com/mikesilvo164/KodiDevKit

another good and easy thing to do is to enable debuglogging in kodi,
the run your skin for a while, basically going through all the windows and dialogs
and check the log for errors and warnings afterwards.

that's what i did this time, and found a few more issues:

**label not defined**: 90940
DialogVideoInfo.xml, line 206


**invalid include**: KeibertzPlus_Fanart_Include
View_902_KeibertzPlus.xml, line 56


**missing image**: _lyretex/gradient_h.png
View_900_Arcade.xml, lines 25, 33, 42


**missing image**: _lyretex/separator2.png
View_900_Arcade.xml, lines 1305, 1570, 1701, 1915


**missing image**: diftest.png
View_900_Arcade.xml, line 715


could you please have a look at those?

**Comment by randallspicher** [comment]
Those should be fixed in the latest release (v7.0.2) I'll update the issue shortly.

For the life of me, I cannot get the kodidevplugin thing to do anything in sublime editor.  Perhaps because of the absence of any documentation that I can find on how to properly install, configure, or use it.  Sublime has a rather steep license fee to boot.  Is it possible to run any of the python checks from the command-line?  (without using the sublime editor?)  I tend to use Eclipse for all my projects.

**Comment by ronie** [comment]
yes, it's possible... it's what i do :)
you should be able to run the script.py file from the cli.
most likely you'd need to alter a few bits and pieces to get it to run as a standalone script,
though i don't exactly recall what and where.

thanx again for the fixes, your skin has now been added to the addon repo:
https://github.com/xbmc/repo-skins/commit/75f1b4cbf2725f1dcbdf53fbd9d1c91bcc100447
