### ISSUE TITLE
Plugin Video of La Capi TV

### ISSUE THREAD

**Issue by b4zz4** [xbmc/repo-skins#364]
- Add-on name: La Capi TV
 - Add-on ID: plugin.video.lacapitv
 - Version number: 1.0.0
 - Kodi/repository version: 19.4 (19.4.0) Matrix
 - Code location URL:  https://git.tuxfamily.org/4232/kodi_plugin_video_lacapitv.git/
 - Revision/tag: 
 - Branch: master

**Comment by enen92** [comment]
This is the repository for skins. We don't accept plugins via issues anymore.
Please send a pull request to [xbmc/repo-plugins](https://github.com/xbmc/repo-plugins/)

**Comment by b4zz4** [comment]
thanks
