### ISSUE TITLE
skin.tetradui 2.0.0 [Nexus]

### ISSUE THREAD

**Issue by gade01** [xbmc/repo-skins#374]
### Add-on details:
This is the initial release of skin.tetradui for Nexus repo.

- **General**
  - Add-on name: TetradUI
  - Add-on ID: skin.tetradui
  - Version number: 2.0.0
  - Kodi/repository version: Nexus
- **Code location**
  - URL: https://github.com/gade01/skin.tetradui
  - Revision/tag: latest
  - Branch: master

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
added to the nexus repo, thx!
https://github.com/xbmc/repo-skins/commit/89b4c7dd0542e0e271b5d3c7804ada19a338d0de
