### ISSUE TITLE
{Submission} skin.ellipsisui

### ISSUE THREAD

**Issue by Ch3dd4rGoblin** [xbmc/repo-skins#377]
> ### Add-on details:
> This is the initial release of skin.ellipsisui for Matrix repo.
> 
> * **General**
>   
>   * Add-on name: EllipsisUI
>   * Add-on ID: skin.ellipsisui
>   * Version number: 2.5.0
>   * Kodi/repository version: Matrix
> * **Code location**
>   
>   * URL: https://github.com/manfeed/skin.EllipsisUI
>   * Revision/tag: latest
>   * Branch: master
> 
> ### Checklist:
> * [x]  My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.
> * [x]  I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
> * [x]  Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by Ch3dd4rGoblin** [comment]
Please make [Ch3dd4rGoblin](https://forum.kodi.tv/member.php?action=profile&uid=465378) and [manfeed](https://forum.kodi.tv/member.php?action=profile&uid=81541) admins of the forum once created, please and thanks

**Comment by ronie** [comment]
nice, i always love it when a new skin gets submitted to the addon repo!

i've had a look at the code and a few things caught my attention:

missing copyright license files for these items:
- credits.mp3
- Ellipsis_time.ttf
without  a proper license file, i have no idea whether we can legally re-distribute those files through our repo :-)

most xml files have Windows style EOL's, please use linux EOL's instead.
perhsaps you can configure you git client to handle this automatically  for you in the future
(https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows)

some undefined labels:
Label not defined: 31032
1080i/SmartPlaylistEditor.xml: line 90

Label not defined: 31042
1080i/SmartPlaylistEditor.xml: line 70

Label not defined: 31043
1080i/SmartPlaylistEditor.xml: line 163

Label not defined: 31059
1080i/GameOSD.xml: line 251

Label not defined: 31060
1080i/GameOSD.xml: line 264

Label not defined: 31096
1080i/DialogSubtitles.xml: line 70

Label not defined: 161
1080i/DialogMusicInfo.xml: line 112
1080i/DialogMusicInfo.xml: line 130
1080i/DialogMusicInfo.xml: line 148
1080i/DialogMusicInfo.xml: line 166
1080i/DialogMusicInfo.xml: line 184
1080i/DialogMusicInfo.xml: line 202
1080i/DialogMusicInfo.xml: line 220
1080i/DialogMusicInfo.xml: line 238
1080i/DialogMusicInfo.xml: line 298
1080i/DialogMusicInfo.xml: line 316
1080i/DialogMusicInfo.xml: line 334
1080i/DialogMusicInfo.xml: line 352
1080i/DialogMusicInfo.xml: line 370
1080i/DialogMusicInfo.xml: line 388
1080i/DialogMusicInfo.xml: line 406
1080i/DialogMusicInfo.xml: line 424
1080i/DialogMusicInfo.xml: line 466
1080i/DialogMusicInfo.xml: line 484
1080i/DialogMusicInfo.xml: line 502
1080i/DialogMusicInfo.xml: line 520
1080i/DialogMusicInfo.xml: line 538
1080i/DialogMusicInfo.xml: line 556
1080i/DialogMusicInfo.xml: line 574
1080i/DialogMusicInfo.xml: line 594

Label not defined: 416
1080i/DialogAddonInfo.xml: line 98
1080i/DialogAddonInfo.xml: line 122
1080i/DialogAddonInfo.xml: line 146
1080i/DialogAddonInfo.xml: line 194
1080i/DialogAddonInfo.xml: line 219

Label not defined: 12323
1080i/DialogNumeric.xml: line 52

**Comment by Ch3dd4rGoblin** [comment]
Thanks so much for reviewing this submission! I believe all those issues have been addressed and has been updated to 2.5.1

**Comment by ronie** [comment]
added to the Matrix repo, thx!
https://github.com/xbmc/repo-skins/commit/de58a72a95df7bb4cf4db28e9f358be502b1ab82

**Comment by Ch3dd4rGoblin** [comment]
There is a widespread issue with the EllipsisUI release.
https://forum.kodi.tv/showthread.php?tid=368248&page=3
It seems as though the textures are corrupt but the same version can be manually installed without issues. Can you look into this and see if it can be resolved? I'll fill out a new ticket if needed but it will be a long while until I can get at my pc and do it.
Thank you!

**Comment by ronie** [comment]
i can reproduce it, which is a good start...
will have a look if i can figure it out

**Comment by ronie** [comment]
just so we're on the same page:
as far is i can tell right now, it's just a single texture which got corrupted.
if you enable 'Hide Vignette Edges' in Skin Settings, everything looks ok to me.

can you please confirm?

**Comment by Ch3dd4rGoblin** [comment]
Thanks for having a look. Yes it does appear that solves the issue.
I'll update the thread to mention this as a temporary solution.
As for fixing it,  do you think this is caused from some issue when all the textures get packed into their textures file? (.xbt if I remember correctly). 
We'll have a look into it regardless and get it fixed and update as soon as possible.

thank you again

**Comment by ronie** [comment]
yes, the problem image is filter_edges.png
it has a bit depth of 16, which our Texturepacker can't handle.

please convert the image to 8-bit and create a new issue so i can pull the updated skin into our repo.

**Comment by Ch3dd4rGoblin** [comment]
thx, will do :)
