### ISSUE TITLE
[update] skin.ellipsisui 2.5.2

### ISSUE THREAD

**Issue by Ch3dd4rGoblin** [xbmc/repo-skins#378]
> Add-on details:
> 
> ```
> General
>     Add-on name: EllipsisUI
>     Add-on ID: skin.ellipsisui
>     Version number: 2.5.2
>     Kodi/repository version: Matrix
> 
> Code location
>     URL: https://github.com/manfeed/skin.EllipsisUI
>     Revision/tag: 6fdd449ac17314133939ea59e113cd4c288f3464
>     Branch: Master
> ```
> 
> Description of changes:
> 
> ```
> Converted filter_edges.png to 8-bit so it would play nicely with texture packer.
> ```
> 
> Checklist:
> 
> ```
> [x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.
> [x ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
> [x ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0
> ```

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/1ab7eb3c49f7f8efa8561241d0af17c7666762ab
