### ISSUE TITLE
[update] skin.quartz 5.19.1

### ISSUE THREAD

**Issue by nonJon** [xbmc/repo-skins#379]
### Add-on details:

- **General**
  - Add-on name: Quartz
  - Add-on ID: skin.quartz
  - Version number: 5.19.1
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/nonJon/skin.quartz/tree/matrix
  - Revision/tag: latest
  - Branch: matrix

### Description of changes:

bug fixes

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
thanx for the update!

hope you can fix these two minor issues:
DialogPVRChannelManager.xml, line 1
please remove the empty first line (the xml declaration needs to be one the first line of the file)

script-globalsearch.xml, line 123:
please add a space between the 'id' and 'description' attributes

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/a9acc0263573f569a18a6bf822d46760003bc5b4
