### ISSUE TITLE
[release] skin.quartz 5.20.0

### ISSUE THREAD

**Issue by nonJon** [xbmc/repo-skins#380]
### Add-on details:

- **General**
  - Add-on name: Quartz
  - Add-on ID: skin.quartz
  - Version number: 5.20.0
  - Kodi/repository version: nexus

- **Code location**
  - URL: https://github.com/nonJon/skin.quartz
  - Revision/tag: latest
  - Branch: master

### Description of changes:

nexus initial 

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
same request as for the matrix pull request:
DialogPVRChannelManager.xml, line 1
please remove the empty first line (the xml declaration needs to be one the first line of the file)

script-globalsearch.xml, line 123:
please add a space between the 'id' and 'description' attributes

**Comment by nonJon** [comment]
fixed both PRs thx

**Comment by ronie** [comment]
added to the nexus repo, thx!
https://github.com/xbmc/repo-skins/commit/7174756e26f61209ab45475b34ca942115d8d987
