### ISSUE TITLE
Skin Aeon MQ 9

### ISSUE THREAD

**Issue by AeonMQ** [xbmc/repo-skins#387]
### Add-on details:

- **General**
  - Add-on name: Aeon MQ 9
  - Add-on ID: skin.aeonmq9
  - Version number: 1.6.0
  - Kodi/repository version: Matrix

- **Code location**
  - URL: https://drive.google.com/drive/folders/1eccb0ty8CHnJTZ10kCNAIjKBvSmWeupX?usp=sharing
  - Revision/tag: 0
  - Branch: master

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
great, would be nice to have aeon mq back in our repo!

could you please have a look at these issues:

Include not defined: library_background
xml/MyPVRGuide.xml: line 8

Include not defined: library_background
xml/MyPVRTimers.xml: line 6

Include not defined: library_background
xml/MyPlaylist.xml: line 6

Include not defined: library_background
xml/MyPVRSearch.xml: line 6

Include not defined: library_background
xml/MyPVRRecordings.xml: line 6


Label not defined: 38401
xml/DialogPVRChannelManager.xml: line 116

Label not defined: 38402
xml/DialogPVRChannelManager.xml: line 119

Label not defined: 38406
xml/DialogPVRChannelManager.xml: line 122

Label not defined: 38400
xml/DialogPVRChannelManager.xml: line 125

**Comment by AeonMQ** [comment]
I'm happy to be back.

All fixes ready, please check.

**Comment by ronie** [comment]
added to the matrix repo, thx!
https://github.com/xbmc/repo-skins/commit/6dcd85e85b4c6c2c8bbaec479b9871d89c6f95db

**Comment by AeonMQ** [comment]
I'm happy to be back.

Ronie, please reopen the Aeon MQ area. Currently the skin is in the
archived skins area.

Em seg., 3 de abr. de 2023 às 18:18, ronie ***@***.***>
escreveu:

**Comment by ronie** [comment]
skin subforum has now been restored ;-)
