### ISSUE TITLE
skin.bello.9

### ISSUE THREAD

**Issue by Nessus85100** [xbmc/repo-skins#399]
### Add-on details:
- **General**
  - Add-on name: Bello 9
  - Add-on ID: skin.bello.9
  - Version number: 9.0.0
  - Kodi/repository version: Nexus
- **Code location**
  - URL: https://github.com/Nessus85100/skin.bello.9
  - Revision/tag: Latest
  - Branch: Master

### Description of changes:
https://github.com/Nessus85100/skin.bello.9/commits/master

**Comment by ronie** [comment]
one small issue to fix please:
Font not defined: TextboxFont_20B
720p/includes.xml: line 378

**Comment by Nessus85100** [comment]
Fixed but since i made some last minute fixes maybe you want to do another check?

Sorry about that😁

**Comment by ronie** [comment]
added to the nexus repo, thx!
https://github.com/xbmc/repo-skins/commit/0576e46b878a07873654f19ebaf95ef04423bb55

**Comment by Nessus85100** [comment]
Sorry to bump this but usually how much time is needed to be added to the repo?

I am just asking since it's been 5 days.

Sorry again

Thanks
Nessus

**Comment by ronie** [comment]
it should only take a couple of hours (max) for the skin to appear on the addon repo.
i've asked our server devs to look into it.

**Comment by ronie** [comment]
see: https://github.com/xbmc/repo-skins/pull/401

**Comment by Nessus85100** [comment]
Hey @ronie all good with the official repo... thanks.

Can you please remove Bello 8 from Nexus repo and rename the skin forum from "Bello 8" to just "Bello" ?

Thanks
Nessus

**Comment by ronie** [comment]
i'm afraid removing Bello 8 from the Nexus repo isn't possible.
for the addon repo, we filter addons (skins) by their xbmc.gui version,
since xbmc.gui 5.15 (which Bello 8 uses) is deemed compatible with Nexus,
it is present is this repository.
... in hindsight, this is a bit of a downside if you use a version number in the name of your addon.

as for the forum, not sure who can handle it these days, ever since the forum breach we tidied up permissions quite a bit.
perhaps @KarellenX can handle it?

**Comment by KarellenX** [comment]
@Nessus85100 You want Bello 8 subform renamed to just Bello?

@ronie You should still have admin permissions on the forum. When you get a chance, can you set up your 2FA for admin access.

**Comment by ronie** [comment]
@KarellenX thx! 
i managed to login and handled the requested change (renaming Bello 8 to simply Bello)

**Comment by Nessus85100** [comment]
@ronie @KarellenX 
Thanks for renaming the "Bello 8" subforum. As for both Bello versions in Nexus repo i don't mind. I thought it was simple to remove version 8 but it's not a problem. After all in both versions its stated clearly with which Kodi version are compatible.

All good.

Thanks a lot guys for your time and sorry for the inconvenience.

Cheers
Nessus
