### ISSUE TITLE
[skin.xperience1080] 8.0.0

### ISSUE THREAD

**Issue by xhaggi** [xbmc/repo-skins#418]
### Add-on details:

- **General**
  - Add-on name: `Xperience1080`
  - Add-on ID: `skin.xperience1080`
  - Version number: `8.0.0`
  - Kodi/repository version: `19.x (Matrix)`

- **Code location**
  - URL: https://github.com/xperience1080/skin.xperience1080
  - Revision/tag: https://github.com/xperience1080/skin.xperience1080/releases/tag/8.0.0
  - Branch: `matrix`

### Description of changes:

Release to be compatible with Kodi 19.x (Matrix).

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
thanx for submitting xperience1080 to the addon repo, it's nice to see it back!

i did  few code checks and found these issues:

Font not defined: Font-Condensed-S47
1080i/script-globalsearch.xml: line 1239

Font not defined: Font-Condensed-S47
1080i/script-globalsearch.xml: line 1253

invalid integer value for id: 30x
1080i/Includes_Dialogs.xml: line 592

Label not defined: 161
1080i/MyPVRGuide.xml: line 416

Label not defined: 161
1080i/DialogPVRInfo.xml: line 373

Label not defined: 416
1080i/DialogMusicInfo.xml: line 328

Label not defined: 416
1080i/DialogMusicInfo.xml: line 356

Label not defined: 416
1080i/DialogMusicInfo.xml: line 384

Label not defined: 416
1080i/DialogMusicInfo.xml: line 407

Label not defined: 416
1080i/DialogMusicInfo.xml: line 430

Label not defined: 416
1080i/DialogMusicInfo.xml: line 496

Label not defined: 416
1080i/DialogMusicInfo.xml: line 523

Label not defined: 416
1080i/DialogMusicInfo.xml: line 546

Label not defined: 416
1080i/DialogMusicInfo.xml: line 569

Label not defined: 31354
1080i/script-cu-lrclyrics-main.xml: line 206

Label not defined: 31353
1080i/script-cu-lrclyrics-main.xml: line 255

Label not defined: 42001
1080i/Includes_DialogConfirm.xml: line 206

Label not defined: 416
1080i/DialogAddonInfo.xml: line 331

Label not defined: 416
1080i/DialogAddonInfo.xml: line 358

Label not defined: 416
1080i/DialogAddonInfo.xml: line 381

Label not defined: 416
1080i/DialogAddonInfo.xml: line 404

**Comment by xhaggi** [comment]
Oh, thx. Do you use the [Skin XML Converter + Formatter](http://forum.kodi.tv/showthread.php?tid=132720) to do the code checks?
