### ISSUE TITLE
[Update] skin.phenomenal

### ISSUE THREAD

**Issue by tomer953** [xbmc/repo-skins#45]
Hi Ronie,
it has been a while since I coded for kodi.
but I found some extra time to make phenomenal for Krypton.

I changed what I saw you mentioned in the forum thread, hope it's fine.

*addon - skin.phenomenal
*version - 4.2.0
*url - https://github.com/tomer953/skin.phenomenal
*branch - master
*xbmc version - Krypton
- Latest Commit.

Let me know if something goes wrong, thank you!

**Comment by ronie** [comment]
hi tomer953,

could you fix the path to the screenshots?
what's specified in addon.xml doesn't match the actual folder.

**Comment by tomer953** [comment]
oops.
fixed

**Comment by ronie** [comment]
added to the krypton repo, thx!
https://github.com/xbmc/repo-skins/commit/928e0c626b880bd748faee433283526b165c3310

**Comment by tomer953** [comment]
hi @ronie ,
sorry for posting here.

a lot of users claims that the "switch" to the skin is a little problematic,
it appear for a sec, and then change to the last skin again.

you can look here:
https://github.com/tomer953/skin.phenomenal/issues/2#issuecomment-280854033
in the last two comments....

some said that I should modify the "font.xml" file and change the fontset from Arial to default.
can you confirm that this is the problem?

thank you.

**Comment by ronie** [comment]
it installs and runs without a problem on my end (linux).
there is no requirement to have a fontset with id "default" in your Fonts.xml file.

without a debuglog there's not much help i can provide, i'm afraid.
