### ISSUE TITLE
[UPDATE] skin.ftv 8.0.0

### ISSUE THREAD

**Issue by Hitcher** [xbmc/repo-skins#469]
### Add-on details:

- **General**
  - Add-on name: fTV
  - Add-on ID: skin.ftv
  - Version number: 8.0.0

- **Code location**
  - URL: https://github.com/Hitcher/skin.ftv
  - Branch: Master

### Description of changes:

Omega update

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
mind checking out these issues:

resource.language.en_gb/strings.po (line 1024):
  Syntax error in po file

Includes.xml (line 18):
  Could not find include file Includes_VideoInfoCast.xml

Includes.xml (line 28):
  Could not find include file script-skinviewtypes-includes.xml

**Comment by Hitcher** [comment]
> resource.language.en_gb/strings.po (line 1024): Syntax error in po file
> 
> Includes.xml (line 18): Could not find include file Includes_VideoInfoCast.xml

Both fixed.

> Includes.xml (line 28):
> Could not find include file script-skinviewtypes-includes.xml

This gets creates when you first run the skin.

Thanks.

**Comment by ronie** [comment]
added to the omega repo, thx!
https://github.com/xbmc/repo-skins/commit/d438cc4521e1c9595ef637f292ab1d9743f01079

**Comment by Hitcher** [comment]
Thanks as ever ronie.
