### ISSUE TITLE
[release] skin.bello v10.0.0

### ISSUE THREAD

**Issue by Nessus85100** [xbmc/repo-skins#471]
### Add-on details:
- **General**
  - Add-on name: Bello 10
  - Add-on ID: skin.bello.10
  - Version number: 10.0.0
  - Kodi/repository version: Omega
- **Code location**
  - URL: https://github.com/Nessus85100/skin.bello.10
  - Revision/tag: Latest
  - Branch: Master

### Description of changes:
https://github.com/Nessus85100/skin.bello.10/commits/master

**Comment by ronie** [comment]
added to the omega repo, thx!
https://github.com/xbmc/repo-skins/commit/16bf388e19f42c921ed300ed6f05d311c435d527
