### ISSUE TITLE
[UPDATE] skin.bello v10.0.1

### ISSUE THREAD

**Issue by Nessus85100** [xbmc/repo-skins#477]
### Add-on details:
- **General**
  - Add-on name: Bello 10
  - Add-on ID: skin.bello.10
  - Version number: 10.0.1
  - Kodi/repository version: Omega
- **Code location**
  - URL: https://github.com/Nessus85100/skin.bello.10
  - Revision/tag: Latest
  - Branch: Master

### Description of changes:
https://github.com/Nessus85100/skin.bello.10/commits/master

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/43823874a9c9541f404797b7b341e20d49db8126
