### ISSUE TITLE
[UPDATE] skin.pellucid v1.1.0

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#50]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 1.1.0
- Kodi/repository version: Krypton
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: 36a775f3663e4aca976fd3bd2e2401e7544dcee4
- Branch: master

### Description of changes:
- Various tweaks and GUI updates.
- [NEW] Additional user options for menu customisation added to skin settings
- [NEW] Fullscreen music / video OSD revised.
- [NEW] Added buttons to 'go to artist' and 'go to album' in the fullscreen music options
- [NEW] Party mode added as a default music menu item
- [NEW] Now playing information presentation modified.
- [NEW] Italian translation (many thanks to Peppe_sr)
- [NEW] French translation (many thanks to Seb Boucourt)

### Checklist:
- [ x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [ x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/59a59fc835fbf9a9121b3ad3e62447df13a3e651
