### ISSUE TITLE
[update] skin.titan

### ISSUE THREAD

**Issue by marcelveldt** [xbmc/repo-skins#53]
### Add-on details:
- Add-on name: Titan 
- Add-on ID: skin.titan
- Version number: 3.6.115
- Kodi/repository version: JARVIS
- URL: https://github.com/marcelveldt/skin.titan
- Revision/tag: latest
- Branch: master

### Description of changes:
- Compatability with new skinhelper addons.
- code cleanup/refactor
- smaller footprint because all static content is moved to resource addons.

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document

**Comment by ronie** [comment]
you forgot to remove the resource.skinthemes.titan dependency in the addon.xml file
(also applies to the krypton pr)

rest of the skin looks ok to me.

**Comment by marcelveldt** [comment]
@ronie, fixed !

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/c07514a147a58fe55e043acd1a8b5b45ba4073c7
