### ISSUE TITLE
[Update] skin.apptv

### ISSUE THREAD

**Issue by wyrm65** [xbmc/repo-skins#55]
### Add-on details:

- **General**
  - Add-on name: AppTV
  - Add-on ID: skin.apptv
  - Version number: 1.5.0
  - Kodi/repository version: KRYPTON

- **Code location**
  - URL: https://github.com/wyrm65/skin.apptv
  - Revision/tag: 97dd6a47f62c0a2876aefe3bd6b9fb97fdb0f5e4
  - Branch: master

### Description of changes:

- Changes required for KRYPTON. 
- Changes required for new version of skin.helper script.
- Major refactor of Home screen customization.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
added to the krypton repo, thx!
https://github.com/xbmc/repo-skins/commit/5510f13ee0f480b85ab2af302c7b541cd67394f6
