### ISSUE TITLE
[update] skin.pellucid v1.1.1

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#59]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 1.1.1
- Kodi/repository version: Krypton
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: 15468f6a1f8b043fca9b481cdbe4ae451d0db869
- Branch: master

### Description of changes:
- [FIXED] Aspect ratio incorrect in poster view (thanks wiiija)
- [NEW] Artist slideshow support
- [NEW] Polish translation (thanks Etharr)
- [FIXED] Context menu onback handling in addons (thanks Solbero)
- [FIXED] onback from music visualisation screen
- [NEW] Video Playlists now display in correct content view with title
- [NEW] Music video support
- [NEW] Artwork downloader support
- [NEW] German translation (thanks Matthias)
- Various minor tweaks

### Checklist:
- [ x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [ x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
i noticed all the font files are marked as executable, could you please fix that?

**Comment by chrisbevan** [comment]
Sorry - fixed: 3656009b39f7965ba11c7849940e80d3bed70191

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/08539ed14f9182bf579ef63f1abfbe56012effea
