### ISSUE TITLE
[New] resource.images.languageflags.colour-flat 0.0.1

### ISSUE THREAD

**Issue by jeroenpardon** [xbmc/repo-skins#61]
### Add-on details:

- **General**
  - Add-on name: Language Flags Colour Flat
  - Add-on ID: resource.images.languageflags.colour-flat
  - Version number: 0.0.1
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/jeroenpardon/resource.images.languageflags.colour-flat
  - Revision/tag: a0184bb4fe601bb9161827b91bf5c2fa30f60ac4
  - Branch: master

### Description of changes:
First submission

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
this is not a skin, is it? ;-)
you'll find the recourses repo here: https://github.com/xbmc/repo-resources/

could you add an info file, like this one:
https://github.com/xbmc/repo-resources/blob/jarvis/resource.images.languageflags.colour/info.xml

minor detail, your changelog contains all but a changelog...

**Comment by jeroenpardon** [comment]
crap, sorry about that ;)
