### ISSUE TITLE
[Update] Skin.Pellucid 1.2.0

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#62]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 1.2.1
- Kodi/repository version: Krypton
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: a2f985741a5a1fce7214e0e7577046c81d1a7792
- Branch: master

### Description of changes:
- [NEW] Extended fanart support for video info and seasons (active by default)
- [NEW] 'Media Showcase'. This extension to the video info screen presents media art in a much more engaging way, taking advantage of available media art.
- [NEW] User option: disable extended fanart
- [NEW] Keyboard autocomplete support
- [NEW] Improved playlist display in music view
- Various tweaks and adjustments

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
there's an undefined include, homeSideMenu, in custom_contextMenu.xml

could you look into that?

**Comment by chrisbevan** [comment]
Sorry. Fixed: dae0a4bb2d2db05885d297fc37d8f2ca6b3336df

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/c078cbc63f93a9da52715987ba1b9cf3899341c0
