### ISSUE TITLE
[Update] Skin.Unity 0.6.3

### ISSUE THREAD

**Issue by bumpaneer** [xbmc/repo-skins#63]
### Add-on details:

- **General**
  - Add-on name: Unity
  - Add-on ID: skin.unity
  - Version number: 0.6.3
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/bumpaneer/skin.unity/
  - Revision/tag: caee6e7d819972ddb8114da46ab169cef295ef5e
  - Branch: Krypton

### Description of changes:

- Multiple Aspect Ratio Support
- Improved Mouse Control
- Additional Widget Options
- Additional Font Weight Options

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/d4490ba34567d81f11efafb6d1c5d5e8852044c2

**Comment by Razzeee** [comment]
@bumpaneer 
on a sidenote, your summary might be out of date :)
https://github.com/bumpaneer/skin.unity/blob/Krypton/addon.xml#L24
