### ISSUE TITLE
[update] skin.pellucid v1.2.2

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#75]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 1.2.2
- Kodi/repository version: Krypton
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: 456873d38957e386250d547aed49aedccde69afe
- Branch: master

### Description of changes:
- [NEW] Hebrew Translation (thanks Eric P)
- [NEW] Poster view enabled for online sourced content
- [NEW] Time index direct search added
- Minor tweaks and adjustments

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by BigNoid** [comment]
Thx for the update!
Pulled in with 4bd7db8cf0e10c42fce601acff3ec31d321da82e
For a future update, could you remove ```script-skinshortcuts-includes.xml``` from your tree and add it to your gitignore?

And non-critical:
```
- Font not defined: thumbtitle - 1080i/Includes_mediaShowcase.xml: line 118
- Font not defined: thumbtitle - 1080i/Includes_mediaShowcase.xml: line 127
- Font not defined: thumbtitle - 1080i/MyPrograms.xml: line 47
- Font not defined: thumbtitle - 1080i/MyPrograms.xml: line 103
- Font not defined: itemSubtitle - 1080i/script-globalsearch-main.xml: line 71
- Font not defined: thumbtitle - 1080i/View_Albums.xml: line 59
- Font not defined: thumbtitle - 1080i/View_Albums.xml: line 128
```
