### ISSUE TITLE
[skin.confluence] 4.0.0

### ISSUE THREAD

**Issue by HitcherUK** [xbmc/repo-skins#78]
### Add-on details:

- **General**
  - Add-on name: Confluence
  - Add-on ID: skin.confluence
  - Version number: 4.0.0
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/xbmc/skin.confluence
  - Branch: Master

### Description of changes:

Updated version for Kodi 'Leia'

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
mind fixing this one:

**Unmatched parenthesis:**
Home.xml - line 821: 
!String.IsEmpty(Container(90110).ListItemNoWrap(0).Label

the rest looks ok to me, thx!

**Comment by HitcherUK** [comment]
Fixed, cheers ronie.

**Comment by ronie** [comment]
added to the leia repo, thx!
https://github.com/xbmc/repo-skins/commit/1e9e6ec7f95ecffe3a326f8f36a9afd2c2fab7bb

**Comment by HitcherUK** [comment]
Thanks.
