### ISSUE TITLE
[update] Skin.pellucid v1.2.3

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-skins#85]
- Add-on name: Pellucid
- Add-on ID: skin.pellucid
- Version number: 1.2.3
- Kodi/repository version: Krypton
- URL: https://github.com/chrisbevan/skin.pellucid
- Revision/tag: 982feff1390e004b8201ee5dbf692a26c7403c75
- Branch: master

### Description of changes:
- [FIXED] Fullscreen music activation could hang kodi in some cases
- [FIXED] Incorrect casing on some font calls (thanks BigNoid)
- [FIXED] Audio offset blocked by dialog background (thanks PaulVT / iamgroot)
- [FIXED] Remove script-skinshortcuts-includes.xml from github tree
- [FIXED] Vignette on artist slideshow adjusted to increase brightness
- [FIXED] PVR Channel icon aspect ratio adjusted for wider icon support
- [FIXED] change aspect ratio blocked by dialog background
- [FIXED] "Play DVD" changed to "Play Disc"
- [FIXED] Fullscreen music -> home transition when music is stopped by user
- [FIXED] Reduced font size on edit source dialog
- [NEW] up / down now controls volume in fullscreen musicview
- [NEW] Russian Translation (thanks Vasiliy)
- Various minor tweaks and fixes

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-skins/commit/77a58e4a2208791f3e9dc096f0d08e0cd89b9dfc
